
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model ConsultantTag
 * 
 */
export type ConsultantTag = Prisma.ConsultantTagModel
/**
 * Model Language
 * 
 */
export type Language = Prisma.LanguageModel
/**
 * Model Certification
 * 
 */
export type Certification = Prisma.CertificationModel
/**
 * Model Review
 * 
 */
export type Review = Prisma.ReviewModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Client
 * 
 */
export type Client = Prisma.ClientModel
/**
 * Model UserSlots
 * 
 */
export type UserSlots = Prisma.UserSlotsModel
/**
 * Model Appointment
 * 
 */
export type Appointment = Prisma.AppointmentModel
/**
 * Model Attachment
 * 
 */
export type Attachment = Prisma.AttachmentModel
/**
 * Model Interaction
 * 
 */
export type Interaction = Prisma.InteractionModel
/**
 * Model Commitment
 * 
 */
export type Commitment = Prisma.CommitmentModel
/**
 * Model Case
 * 
 */
export type Case = Prisma.CaseModel
/**
 * Model Task
 * 
 */
export type Task = Prisma.TaskModel
/**
 * Model AuditLog
 * 
 */
export type AuditLog = Prisma.AuditLogModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
/**
 * Model RazorpayWebhook
 * 
 */
export type RazorpayWebhook = Prisma.RazorpayWebhookModel
