
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/ConsultantTag'
export type * from './models/Language'
export type * from './models/Certification'
export type * from './models/Review'
export type * from './models/User'
export type * from './models/Client'
export type * from './models/UserSlots'
export type * from './models/Appointment'
export type * from './models/Attachment'
export type * from './models/Interaction'
export type * from './models/Commitment'
export type * from './models/Case'
export type * from './models/Task'
export type * from './models/AuditLog'
export type * from './models/Payment'
export type * from './models/RazorpayWebhook'
export type * from './commonInputTypes'