
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Attachment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Attachment
 * 
 */
export type AttachmentModel = runtime.Types.Result.DefaultSelection<Prisma.$AttachmentPayload>

export type AggregateAttachment = {
  _count: AttachmentCountAggregateOutputType | null
  _avg: AttachmentAvgAggregateOutputType | null
  _sum: AttachmentSumAggregateOutputType | null
  _min: AttachmentMinAggregateOutputType | null
  _max: AttachmentMaxAggregateOutputType | null
}

export type AttachmentAvgAggregateOutputType = {
  fileSize: number | null
}

export type AttachmentSumAggregateOutputType = {
  fileSize: number | null
}

export type AttachmentMinAggregateOutputType = {
  id: string | null
  userId: string | null
  clientId: string | null
  interactionId: string | null
  taskId: string | null
  appointmentId: string | null
  fileName: string | null
  fileType: string | null
  fileUrl: string | null
  fileSize: number | null
  createdAt: Date | null
}

export type AttachmentMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  clientId: string | null
  interactionId: string | null
  taskId: string | null
  appointmentId: string | null
  fileName: string | null
  fileType: string | null
  fileUrl: string | null
  fileSize: number | null
  createdAt: Date | null
}

export type AttachmentCountAggregateOutputType = {
  id: number
  userId: number
  clientId: number
  interactionId: number
  taskId: number
  appointmentId: number
  fileName: number
  fileType: number
  fileUrl: number
  fileSize: number
  createdAt: number
  _all: number
}


export type AttachmentAvgAggregateInputType = {
  fileSize?: true
}

export type AttachmentSumAggregateInputType = {
  fileSize?: true
}

export type AttachmentMinAggregateInputType = {
  id?: true
  userId?: true
  clientId?: true
  interactionId?: true
  taskId?: true
  appointmentId?: true
  fileName?: true
  fileType?: true
  fileUrl?: true
  fileSize?: true
  createdAt?: true
}

export type AttachmentMaxAggregateInputType = {
  id?: true
  userId?: true
  clientId?: true
  interactionId?: true
  taskId?: true
  appointmentId?: true
  fileName?: true
  fileType?: true
  fileUrl?: true
  fileSize?: true
  createdAt?: true
}

export type AttachmentCountAggregateInputType = {
  id?: true
  userId?: true
  clientId?: true
  interactionId?: true
  taskId?: true
  appointmentId?: true
  fileName?: true
  fileType?: true
  fileUrl?: true
  fileSize?: true
  createdAt?: true
  _all?: true
}

export type AttachmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Attachment to aggregate.
   */
  where?: Prisma.AttachmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Attachments to fetch.
   */
  orderBy?: Prisma.AttachmentOrderByWithRelationInput | Prisma.AttachmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AttachmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Attachments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Attachments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Attachments
  **/
  _count?: true | AttachmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AttachmentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AttachmentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AttachmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AttachmentMaxAggregateInputType
}

export type GetAttachmentAggregateType<T extends AttachmentAggregateArgs> = {
      [P in keyof T & keyof AggregateAttachment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAttachment[P]>
    : Prisma.GetScalarType<T[P], AggregateAttachment[P]>
}




export type AttachmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AttachmentWhereInput
  orderBy?: Prisma.AttachmentOrderByWithAggregationInput | Prisma.AttachmentOrderByWithAggregationInput[]
  by: Prisma.AttachmentScalarFieldEnum[] | Prisma.AttachmentScalarFieldEnum
  having?: Prisma.AttachmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AttachmentCountAggregateInputType | true
  _avg?: AttachmentAvgAggregateInputType
  _sum?: AttachmentSumAggregateInputType
  _min?: AttachmentMinAggregateInputType
  _max?: AttachmentMaxAggregateInputType
}

export type AttachmentGroupByOutputType = {
  id: string
  userId: string | null
  clientId: string | null
  interactionId: string | null
  taskId: string | null
  appointmentId: string | null
  fileName: string
  fileType: string
  fileUrl: string
  fileSize: number | null
  createdAt: Date
  _count: AttachmentCountAggregateOutputType | null
  _avg: AttachmentAvgAggregateOutputType | null
  _sum: AttachmentSumAggregateOutputType | null
  _min: AttachmentMinAggregateOutputType | null
  _max: AttachmentMaxAggregateOutputType | null
}

export type GetAttachmentGroupByPayload<T extends AttachmentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AttachmentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AttachmentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AttachmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AttachmentGroupByOutputType[P]>
      }
    >
  >



export type AttachmentWhereInput = {
  AND?: Prisma.AttachmentWhereInput | Prisma.AttachmentWhereInput[]
  OR?: Prisma.AttachmentWhereInput[]
  NOT?: Prisma.AttachmentWhereInput | Prisma.AttachmentWhereInput[]
  id?: Prisma.StringFilter<"Attachment"> | string
  userId?: Prisma.StringNullableFilter<"Attachment"> | string | null
  clientId?: Prisma.StringNullableFilter<"Attachment"> | string | null
  interactionId?: Prisma.StringNullableFilter<"Attachment"> | string | null
  taskId?: Prisma.StringNullableFilter<"Attachment"> | string | null
  appointmentId?: Prisma.StringNullableFilter<"Attachment"> | string | null
  fileName?: Prisma.StringFilter<"Attachment"> | string
  fileType?: Prisma.StringFilter<"Attachment"> | string
  fileUrl?: Prisma.StringFilter<"Attachment"> | string
  fileSize?: Prisma.IntNullableFilter<"Attachment"> | number | null
  createdAt?: Prisma.DateTimeFilter<"Attachment"> | Date | string
  client?: Prisma.XOR<Prisma.ClientNullableScalarRelationFilter, Prisma.ClientWhereInput> | null
  interaction?: Prisma.XOR<Prisma.InteractionNullableScalarRelationFilter, Prisma.InteractionWhereInput> | null
  task?: Prisma.XOR<Prisma.TaskNullableScalarRelationFilter, Prisma.TaskWhereInput> | null
  appointment?: Prisma.XOR<Prisma.AppointmentNullableScalarRelationFilter, Prisma.AppointmentWhereInput> | null
}

export type AttachmentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  clientId?: Prisma.SortOrderInput | Prisma.SortOrder
  interactionId?: Prisma.SortOrderInput | Prisma.SortOrder
  taskId?: Prisma.SortOrderInput | Prisma.SortOrder
  appointmentId?: Prisma.SortOrderInput | Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  fileSize?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  client?: Prisma.ClientOrderByWithRelationInput
  interaction?: Prisma.InteractionOrderByWithRelationInput
  task?: Prisma.TaskOrderByWithRelationInput
  appointment?: Prisma.AppointmentOrderByWithRelationInput
}

export type AttachmentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AttachmentWhereInput | Prisma.AttachmentWhereInput[]
  OR?: Prisma.AttachmentWhereInput[]
  NOT?: Prisma.AttachmentWhereInput | Prisma.AttachmentWhereInput[]
  userId?: Prisma.StringNullableFilter<"Attachment"> | string | null
  clientId?: Prisma.StringNullableFilter<"Attachment"> | string | null
  interactionId?: Prisma.StringNullableFilter<"Attachment"> | string | null
  taskId?: Prisma.StringNullableFilter<"Attachment"> | string | null
  appointmentId?: Prisma.StringNullableFilter<"Attachment"> | string | null
  fileName?: Prisma.StringFilter<"Attachment"> | string
  fileType?: Prisma.StringFilter<"Attachment"> | string
  fileUrl?: Prisma.StringFilter<"Attachment"> | string
  fileSize?: Prisma.IntNullableFilter<"Attachment"> | number | null
  createdAt?: Prisma.DateTimeFilter<"Attachment"> | Date | string
  client?: Prisma.XOR<Prisma.ClientNullableScalarRelationFilter, Prisma.ClientWhereInput> | null
  interaction?: Prisma.XOR<Prisma.InteractionNullableScalarRelationFilter, Prisma.InteractionWhereInput> | null
  task?: Prisma.XOR<Prisma.TaskNullableScalarRelationFilter, Prisma.TaskWhereInput> | null
  appointment?: Prisma.XOR<Prisma.AppointmentNullableScalarRelationFilter, Prisma.AppointmentWhereInput> | null
}, "id">

export type AttachmentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  clientId?: Prisma.SortOrderInput | Prisma.SortOrder
  interactionId?: Prisma.SortOrderInput | Prisma.SortOrder
  taskId?: Prisma.SortOrderInput | Prisma.SortOrder
  appointmentId?: Prisma.SortOrderInput | Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  fileSize?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AttachmentCountOrderByAggregateInput
  _avg?: Prisma.AttachmentAvgOrderByAggregateInput
  _max?: Prisma.AttachmentMaxOrderByAggregateInput
  _min?: Prisma.AttachmentMinOrderByAggregateInput
  _sum?: Prisma.AttachmentSumOrderByAggregateInput
}

export type AttachmentScalarWhereWithAggregatesInput = {
  AND?: Prisma.AttachmentScalarWhereWithAggregatesInput | Prisma.AttachmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.AttachmentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AttachmentScalarWhereWithAggregatesInput | Prisma.AttachmentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Attachment"> | string
  userId?: Prisma.StringNullableWithAggregatesFilter<"Attachment"> | string | null
  clientId?: Prisma.StringNullableWithAggregatesFilter<"Attachment"> | string | null
  interactionId?: Prisma.StringNullableWithAggregatesFilter<"Attachment"> | string | null
  taskId?: Prisma.StringNullableWithAggregatesFilter<"Attachment"> | string | null
  appointmentId?: Prisma.StringNullableWithAggregatesFilter<"Attachment"> | string | null
  fileName?: Prisma.StringWithAggregatesFilter<"Attachment"> | string
  fileType?: Prisma.StringWithAggregatesFilter<"Attachment"> | string
  fileUrl?: Prisma.StringWithAggregatesFilter<"Attachment"> | string
  fileSize?: Prisma.IntNullableWithAggregatesFilter<"Attachment"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Attachment"> | Date | string
}

export type AttachmentCreateInput = {
  id?: string
  userId?: string | null
  fileName: string
  fileType: string
  fileUrl: string
  fileSize?: number | null
  createdAt?: Date | string
  client?: Prisma.ClientCreateNestedOneWithoutAttachmentsInput
  interaction?: Prisma.InteractionCreateNestedOneWithoutAttachmentsInput
  task?: Prisma.TaskCreateNestedOneWithoutAttachmentsInput
  appointment?: Prisma.AppointmentCreateNestedOneWithoutAppointmentDocsInput
}

export type AttachmentUncheckedCreateInput = {
  id?: string
  userId?: string | null
  clientId?: string | null
  interactionId?: string | null
  taskId?: string | null
  appointmentId?: string | null
  fileName: string
  fileType: string
  fileUrl: string
  fileSize?: number | null
  createdAt?: Date | string
}

export type AttachmentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  client?: Prisma.ClientUpdateOneWithoutAttachmentsNestedInput
  interaction?: Prisma.InteractionUpdateOneWithoutAttachmentsNestedInput
  task?: Prisma.TaskUpdateOneWithoutAttachmentsNestedInput
  appointment?: Prisma.AppointmentUpdateOneWithoutAppointmentDocsNestedInput
}

export type AttachmentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  taskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  appointmentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AttachmentCreateManyInput = {
  id?: string
  userId?: string | null
  clientId?: string | null
  interactionId?: string | null
  taskId?: string | null
  appointmentId?: string | null
  fileName: string
  fileType: string
  fileUrl: string
  fileSize?: number | null
  createdAt?: Date | string
}

export type AttachmentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AttachmentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  taskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  appointmentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AttachmentListRelationFilter = {
  every?: Prisma.AttachmentWhereInput
  some?: Prisma.AttachmentWhereInput
  none?: Prisma.AttachmentWhereInput
}

export type AttachmentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AttachmentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  interactionId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AttachmentAvgOrderByAggregateInput = {
  fileSize?: Prisma.SortOrder
}

export type AttachmentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  interactionId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AttachmentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  interactionId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  fileType?: Prisma.SortOrder
  fileUrl?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AttachmentSumOrderByAggregateInput = {
  fileSize?: Prisma.SortOrder
}

export type AttachmentCreateNestedManyWithoutClientInput = {
  create?: Prisma.XOR<Prisma.AttachmentCreateWithoutClientInput, Prisma.AttachmentUncheckedCreateWithoutClientInput> | Prisma.AttachmentCreateWithoutClientInput[] | Prisma.AttachmentUncheckedCreateWithoutClientInput[]
  connectOrCreate?: Prisma.AttachmentCreateOrConnectWithoutClientInput | Prisma.AttachmentCreateOrConnectWithoutClientInput[]
  createMany?: Prisma.AttachmentCreateManyClientInputEnvelope
  connect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
}

export type AttachmentUncheckedCreateNestedManyWithoutClientInput = {
  create?: Prisma.XOR<Prisma.AttachmentCreateWithoutClientInput, Prisma.AttachmentUncheckedCreateWithoutClientInput> | Prisma.AttachmentCreateWithoutClientInput[] | Prisma.AttachmentUncheckedCreateWithoutClientInput[]
  connectOrCreate?: Prisma.AttachmentCreateOrConnectWithoutClientInput | Prisma.AttachmentCreateOrConnectWithoutClientInput[]
  createMany?: Prisma.AttachmentCreateManyClientInputEnvelope
  connect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
}

export type AttachmentUpdateManyWithoutClientNestedInput = {
  create?: Prisma.XOR<Prisma.AttachmentCreateWithoutClientInput, Prisma.AttachmentUncheckedCreateWithoutClientInput> | Prisma.AttachmentCreateWithoutClientInput[] | Prisma.AttachmentUncheckedCreateWithoutClientInput[]
  connectOrCreate?: Prisma.AttachmentCreateOrConnectWithoutClientInput | Prisma.AttachmentCreateOrConnectWithoutClientInput[]
  upsert?: Prisma.AttachmentUpsertWithWhereUniqueWithoutClientInput | Prisma.AttachmentUpsertWithWhereUniqueWithoutClientInput[]
  createMany?: Prisma.AttachmentCreateManyClientInputEnvelope
  set?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  disconnect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  delete?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  connect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  update?: Prisma.AttachmentUpdateWithWhereUniqueWithoutClientInput | Prisma.AttachmentUpdateWithWhereUniqueWithoutClientInput[]
  updateMany?: Prisma.AttachmentUpdateManyWithWhereWithoutClientInput | Prisma.AttachmentUpdateManyWithWhereWithoutClientInput[]
  deleteMany?: Prisma.AttachmentScalarWhereInput | Prisma.AttachmentScalarWhereInput[]
}

export type AttachmentUncheckedUpdateManyWithoutClientNestedInput = {
  create?: Prisma.XOR<Prisma.AttachmentCreateWithoutClientInput, Prisma.AttachmentUncheckedCreateWithoutClientInput> | Prisma.AttachmentCreateWithoutClientInput[] | Prisma.AttachmentUncheckedCreateWithoutClientInput[]
  connectOrCreate?: Prisma.AttachmentCreateOrConnectWithoutClientInput | Prisma.AttachmentCreateOrConnectWithoutClientInput[]
  upsert?: Prisma.AttachmentUpsertWithWhereUniqueWithoutClientInput | Prisma.AttachmentUpsertWithWhereUniqueWithoutClientInput[]
  createMany?: Prisma.AttachmentCreateManyClientInputEnvelope
  set?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  disconnect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  delete?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  connect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  update?: Prisma.AttachmentUpdateWithWhereUniqueWithoutClientInput | Prisma.AttachmentUpdateWithWhereUniqueWithoutClientInput[]
  updateMany?: Prisma.AttachmentUpdateManyWithWhereWithoutClientInput | Prisma.AttachmentUpdateManyWithWhereWithoutClientInput[]
  deleteMany?: Prisma.AttachmentScalarWhereInput | Prisma.AttachmentScalarWhereInput[]
}

export type AttachmentCreateNestedManyWithoutAppointmentInput = {
  create?: Prisma.XOR<Prisma.AttachmentCreateWithoutAppointmentInput, Prisma.AttachmentUncheckedCreateWithoutAppointmentInput> | Prisma.AttachmentCreateWithoutAppointmentInput[] | Prisma.AttachmentUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.AttachmentCreateOrConnectWithoutAppointmentInput | Prisma.AttachmentCreateOrConnectWithoutAppointmentInput[]
  createMany?: Prisma.AttachmentCreateManyAppointmentInputEnvelope
  connect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
}

export type AttachmentUncheckedCreateNestedManyWithoutAppointmentInput = {
  create?: Prisma.XOR<Prisma.AttachmentCreateWithoutAppointmentInput, Prisma.AttachmentUncheckedCreateWithoutAppointmentInput> | Prisma.AttachmentCreateWithoutAppointmentInput[] | Prisma.AttachmentUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.AttachmentCreateOrConnectWithoutAppointmentInput | Prisma.AttachmentCreateOrConnectWithoutAppointmentInput[]
  createMany?: Prisma.AttachmentCreateManyAppointmentInputEnvelope
  connect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
}

export type AttachmentUpdateManyWithoutAppointmentNestedInput = {
  create?: Prisma.XOR<Prisma.AttachmentCreateWithoutAppointmentInput, Prisma.AttachmentUncheckedCreateWithoutAppointmentInput> | Prisma.AttachmentCreateWithoutAppointmentInput[] | Prisma.AttachmentUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.AttachmentCreateOrConnectWithoutAppointmentInput | Prisma.AttachmentCreateOrConnectWithoutAppointmentInput[]
  upsert?: Prisma.AttachmentUpsertWithWhereUniqueWithoutAppointmentInput | Prisma.AttachmentUpsertWithWhereUniqueWithoutAppointmentInput[]
  createMany?: Prisma.AttachmentCreateManyAppointmentInputEnvelope
  set?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  disconnect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  delete?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  connect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  update?: Prisma.AttachmentUpdateWithWhereUniqueWithoutAppointmentInput | Prisma.AttachmentUpdateWithWhereUniqueWithoutAppointmentInput[]
  updateMany?: Prisma.AttachmentUpdateManyWithWhereWithoutAppointmentInput | Prisma.AttachmentUpdateManyWithWhereWithoutAppointmentInput[]
  deleteMany?: Prisma.AttachmentScalarWhereInput | Prisma.AttachmentScalarWhereInput[]
}

export type AttachmentUncheckedUpdateManyWithoutAppointmentNestedInput = {
  create?: Prisma.XOR<Prisma.AttachmentCreateWithoutAppointmentInput, Prisma.AttachmentUncheckedCreateWithoutAppointmentInput> | Prisma.AttachmentCreateWithoutAppointmentInput[] | Prisma.AttachmentUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.AttachmentCreateOrConnectWithoutAppointmentInput | Prisma.AttachmentCreateOrConnectWithoutAppointmentInput[]
  upsert?: Prisma.AttachmentUpsertWithWhereUniqueWithoutAppointmentInput | Prisma.AttachmentUpsertWithWhereUniqueWithoutAppointmentInput[]
  createMany?: Prisma.AttachmentCreateManyAppointmentInputEnvelope
  set?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  disconnect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  delete?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  connect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  update?: Prisma.AttachmentUpdateWithWhereUniqueWithoutAppointmentInput | Prisma.AttachmentUpdateWithWhereUniqueWithoutAppointmentInput[]
  updateMany?: Prisma.AttachmentUpdateManyWithWhereWithoutAppointmentInput | Prisma.AttachmentUpdateManyWithWhereWithoutAppointmentInput[]
  deleteMany?: Prisma.AttachmentScalarWhereInput | Prisma.AttachmentScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type AttachmentCreateNestedManyWithoutInteractionInput = {
  create?: Prisma.XOR<Prisma.AttachmentCreateWithoutInteractionInput, Prisma.AttachmentUncheckedCreateWithoutInteractionInput> | Prisma.AttachmentCreateWithoutInteractionInput[] | Prisma.AttachmentUncheckedCreateWithoutInteractionInput[]
  connectOrCreate?: Prisma.AttachmentCreateOrConnectWithoutInteractionInput | Prisma.AttachmentCreateOrConnectWithoutInteractionInput[]
  createMany?: Prisma.AttachmentCreateManyInteractionInputEnvelope
  connect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
}

export type AttachmentUncheckedCreateNestedManyWithoutInteractionInput = {
  create?: Prisma.XOR<Prisma.AttachmentCreateWithoutInteractionInput, Prisma.AttachmentUncheckedCreateWithoutInteractionInput> | Prisma.AttachmentCreateWithoutInteractionInput[] | Prisma.AttachmentUncheckedCreateWithoutInteractionInput[]
  connectOrCreate?: Prisma.AttachmentCreateOrConnectWithoutInteractionInput | Prisma.AttachmentCreateOrConnectWithoutInteractionInput[]
  createMany?: Prisma.AttachmentCreateManyInteractionInputEnvelope
  connect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
}

export type AttachmentUpdateManyWithoutInteractionNestedInput = {
  create?: Prisma.XOR<Prisma.AttachmentCreateWithoutInteractionInput, Prisma.AttachmentUncheckedCreateWithoutInteractionInput> | Prisma.AttachmentCreateWithoutInteractionInput[] | Prisma.AttachmentUncheckedCreateWithoutInteractionInput[]
  connectOrCreate?: Prisma.AttachmentCreateOrConnectWithoutInteractionInput | Prisma.AttachmentCreateOrConnectWithoutInteractionInput[]
  upsert?: Prisma.AttachmentUpsertWithWhereUniqueWithoutInteractionInput | Prisma.AttachmentUpsertWithWhereUniqueWithoutInteractionInput[]
  createMany?: Prisma.AttachmentCreateManyInteractionInputEnvelope
  set?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  disconnect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  delete?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  connect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  update?: Prisma.AttachmentUpdateWithWhereUniqueWithoutInteractionInput | Prisma.AttachmentUpdateWithWhereUniqueWithoutInteractionInput[]
  updateMany?: Prisma.AttachmentUpdateManyWithWhereWithoutInteractionInput | Prisma.AttachmentUpdateManyWithWhereWithoutInteractionInput[]
  deleteMany?: Prisma.AttachmentScalarWhereInput | Prisma.AttachmentScalarWhereInput[]
}

export type AttachmentUncheckedUpdateManyWithoutInteractionNestedInput = {
  create?: Prisma.XOR<Prisma.AttachmentCreateWithoutInteractionInput, Prisma.AttachmentUncheckedCreateWithoutInteractionInput> | Prisma.AttachmentCreateWithoutInteractionInput[] | Prisma.AttachmentUncheckedCreateWithoutInteractionInput[]
  connectOrCreate?: Prisma.AttachmentCreateOrConnectWithoutInteractionInput | Prisma.AttachmentCreateOrConnectWithoutInteractionInput[]
  upsert?: Prisma.AttachmentUpsertWithWhereUniqueWithoutInteractionInput | Prisma.AttachmentUpsertWithWhereUniqueWithoutInteractionInput[]
  createMany?: Prisma.AttachmentCreateManyInteractionInputEnvelope
  set?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  disconnect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  delete?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  connect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  update?: Prisma.AttachmentUpdateWithWhereUniqueWithoutInteractionInput | Prisma.AttachmentUpdateWithWhereUniqueWithoutInteractionInput[]
  updateMany?: Prisma.AttachmentUpdateManyWithWhereWithoutInteractionInput | Prisma.AttachmentUpdateManyWithWhereWithoutInteractionInput[]
  deleteMany?: Prisma.AttachmentScalarWhereInput | Prisma.AttachmentScalarWhereInput[]
}

export type AttachmentCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.AttachmentCreateWithoutTaskInput, Prisma.AttachmentUncheckedCreateWithoutTaskInput> | Prisma.AttachmentCreateWithoutTaskInput[] | Prisma.AttachmentUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.AttachmentCreateOrConnectWithoutTaskInput | Prisma.AttachmentCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.AttachmentCreateManyTaskInputEnvelope
  connect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
}

export type AttachmentUncheckedCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.AttachmentCreateWithoutTaskInput, Prisma.AttachmentUncheckedCreateWithoutTaskInput> | Prisma.AttachmentCreateWithoutTaskInput[] | Prisma.AttachmentUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.AttachmentCreateOrConnectWithoutTaskInput | Prisma.AttachmentCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.AttachmentCreateManyTaskInputEnvelope
  connect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
}

export type AttachmentUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.AttachmentCreateWithoutTaskInput, Prisma.AttachmentUncheckedCreateWithoutTaskInput> | Prisma.AttachmentCreateWithoutTaskInput[] | Prisma.AttachmentUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.AttachmentCreateOrConnectWithoutTaskInput | Prisma.AttachmentCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.AttachmentUpsertWithWhereUniqueWithoutTaskInput | Prisma.AttachmentUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.AttachmentCreateManyTaskInputEnvelope
  set?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  disconnect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  delete?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  connect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  update?: Prisma.AttachmentUpdateWithWhereUniqueWithoutTaskInput | Prisma.AttachmentUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.AttachmentUpdateManyWithWhereWithoutTaskInput | Prisma.AttachmentUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.AttachmentScalarWhereInput | Prisma.AttachmentScalarWhereInput[]
}

export type AttachmentUncheckedUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.AttachmentCreateWithoutTaskInput, Prisma.AttachmentUncheckedCreateWithoutTaskInput> | Prisma.AttachmentCreateWithoutTaskInput[] | Prisma.AttachmentUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.AttachmentCreateOrConnectWithoutTaskInput | Prisma.AttachmentCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.AttachmentUpsertWithWhereUniqueWithoutTaskInput | Prisma.AttachmentUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.AttachmentCreateManyTaskInputEnvelope
  set?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  disconnect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  delete?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  connect?: Prisma.AttachmentWhereUniqueInput | Prisma.AttachmentWhereUniqueInput[]
  update?: Prisma.AttachmentUpdateWithWhereUniqueWithoutTaskInput | Prisma.AttachmentUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.AttachmentUpdateManyWithWhereWithoutTaskInput | Prisma.AttachmentUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.AttachmentScalarWhereInput | Prisma.AttachmentScalarWhereInput[]
}

export type AttachmentCreateWithoutClientInput = {
  id?: string
  userId?: string | null
  fileName: string
  fileType: string
  fileUrl: string
  fileSize?: number | null
  createdAt?: Date | string
  interaction?: Prisma.InteractionCreateNestedOneWithoutAttachmentsInput
  task?: Prisma.TaskCreateNestedOneWithoutAttachmentsInput
  appointment?: Prisma.AppointmentCreateNestedOneWithoutAppointmentDocsInput
}

export type AttachmentUncheckedCreateWithoutClientInput = {
  id?: string
  userId?: string | null
  interactionId?: string | null
  taskId?: string | null
  appointmentId?: string | null
  fileName: string
  fileType: string
  fileUrl: string
  fileSize?: number | null
  createdAt?: Date | string
}

export type AttachmentCreateOrConnectWithoutClientInput = {
  where: Prisma.AttachmentWhereUniqueInput
  create: Prisma.XOR<Prisma.AttachmentCreateWithoutClientInput, Prisma.AttachmentUncheckedCreateWithoutClientInput>
}

export type AttachmentCreateManyClientInputEnvelope = {
  data: Prisma.AttachmentCreateManyClientInput | Prisma.AttachmentCreateManyClientInput[]
  skipDuplicates?: boolean
}

export type AttachmentUpsertWithWhereUniqueWithoutClientInput = {
  where: Prisma.AttachmentWhereUniqueInput
  update: Prisma.XOR<Prisma.AttachmentUpdateWithoutClientInput, Prisma.AttachmentUncheckedUpdateWithoutClientInput>
  create: Prisma.XOR<Prisma.AttachmentCreateWithoutClientInput, Prisma.AttachmentUncheckedCreateWithoutClientInput>
}

export type AttachmentUpdateWithWhereUniqueWithoutClientInput = {
  where: Prisma.AttachmentWhereUniqueInput
  data: Prisma.XOR<Prisma.AttachmentUpdateWithoutClientInput, Prisma.AttachmentUncheckedUpdateWithoutClientInput>
}

export type AttachmentUpdateManyWithWhereWithoutClientInput = {
  where: Prisma.AttachmentScalarWhereInput
  data: Prisma.XOR<Prisma.AttachmentUpdateManyMutationInput, Prisma.AttachmentUncheckedUpdateManyWithoutClientInput>
}

export type AttachmentScalarWhereInput = {
  AND?: Prisma.AttachmentScalarWhereInput | Prisma.AttachmentScalarWhereInput[]
  OR?: Prisma.AttachmentScalarWhereInput[]
  NOT?: Prisma.AttachmentScalarWhereInput | Prisma.AttachmentScalarWhereInput[]
  id?: Prisma.StringFilter<"Attachment"> | string
  userId?: Prisma.StringNullableFilter<"Attachment"> | string | null
  clientId?: Prisma.StringNullableFilter<"Attachment"> | string | null
  interactionId?: Prisma.StringNullableFilter<"Attachment"> | string | null
  taskId?: Prisma.StringNullableFilter<"Attachment"> | string | null
  appointmentId?: Prisma.StringNullableFilter<"Attachment"> | string | null
  fileName?: Prisma.StringFilter<"Attachment"> | string
  fileType?: Prisma.StringFilter<"Attachment"> | string
  fileUrl?: Prisma.StringFilter<"Attachment"> | string
  fileSize?: Prisma.IntNullableFilter<"Attachment"> | number | null
  createdAt?: Prisma.DateTimeFilter<"Attachment"> | Date | string
}

export type AttachmentCreateWithoutAppointmentInput = {
  id?: string
  userId?: string | null
  fileName: string
  fileType: string
  fileUrl: string
  fileSize?: number | null
  createdAt?: Date | string
  client?: Prisma.ClientCreateNestedOneWithoutAttachmentsInput
  interaction?: Prisma.InteractionCreateNestedOneWithoutAttachmentsInput
  task?: Prisma.TaskCreateNestedOneWithoutAttachmentsInput
}

export type AttachmentUncheckedCreateWithoutAppointmentInput = {
  id?: string
  userId?: string | null
  clientId?: string | null
  interactionId?: string | null
  taskId?: string | null
  fileName: string
  fileType: string
  fileUrl: string
  fileSize?: number | null
  createdAt?: Date | string
}

export type AttachmentCreateOrConnectWithoutAppointmentInput = {
  where: Prisma.AttachmentWhereUniqueInput
  create: Prisma.XOR<Prisma.AttachmentCreateWithoutAppointmentInput, Prisma.AttachmentUncheckedCreateWithoutAppointmentInput>
}

export type AttachmentCreateManyAppointmentInputEnvelope = {
  data: Prisma.AttachmentCreateManyAppointmentInput | Prisma.AttachmentCreateManyAppointmentInput[]
  skipDuplicates?: boolean
}

export type AttachmentUpsertWithWhereUniqueWithoutAppointmentInput = {
  where: Prisma.AttachmentWhereUniqueInput
  update: Prisma.XOR<Prisma.AttachmentUpdateWithoutAppointmentInput, Prisma.AttachmentUncheckedUpdateWithoutAppointmentInput>
  create: Prisma.XOR<Prisma.AttachmentCreateWithoutAppointmentInput, Prisma.AttachmentUncheckedCreateWithoutAppointmentInput>
}

export type AttachmentUpdateWithWhereUniqueWithoutAppointmentInput = {
  where: Prisma.AttachmentWhereUniqueInput
  data: Prisma.XOR<Prisma.AttachmentUpdateWithoutAppointmentInput, Prisma.AttachmentUncheckedUpdateWithoutAppointmentInput>
}

export type AttachmentUpdateManyWithWhereWithoutAppointmentInput = {
  where: Prisma.AttachmentScalarWhereInput
  data: Prisma.XOR<Prisma.AttachmentUpdateManyMutationInput, Prisma.AttachmentUncheckedUpdateManyWithoutAppointmentInput>
}

export type AttachmentCreateWithoutInteractionInput = {
  id?: string
  userId?: string | null
  fileName: string
  fileType: string
  fileUrl: string
  fileSize?: number | null
  createdAt?: Date | string
  client?: Prisma.ClientCreateNestedOneWithoutAttachmentsInput
  task?: Prisma.TaskCreateNestedOneWithoutAttachmentsInput
  appointment?: Prisma.AppointmentCreateNestedOneWithoutAppointmentDocsInput
}

export type AttachmentUncheckedCreateWithoutInteractionInput = {
  id?: string
  userId?: string | null
  clientId?: string | null
  taskId?: string | null
  appointmentId?: string | null
  fileName: string
  fileType: string
  fileUrl: string
  fileSize?: number | null
  createdAt?: Date | string
}

export type AttachmentCreateOrConnectWithoutInteractionInput = {
  where: Prisma.AttachmentWhereUniqueInput
  create: Prisma.XOR<Prisma.AttachmentCreateWithoutInteractionInput, Prisma.AttachmentUncheckedCreateWithoutInteractionInput>
}

export type AttachmentCreateManyInteractionInputEnvelope = {
  data: Prisma.AttachmentCreateManyInteractionInput | Prisma.AttachmentCreateManyInteractionInput[]
  skipDuplicates?: boolean
}

export type AttachmentUpsertWithWhereUniqueWithoutInteractionInput = {
  where: Prisma.AttachmentWhereUniqueInput
  update: Prisma.XOR<Prisma.AttachmentUpdateWithoutInteractionInput, Prisma.AttachmentUncheckedUpdateWithoutInteractionInput>
  create: Prisma.XOR<Prisma.AttachmentCreateWithoutInteractionInput, Prisma.AttachmentUncheckedCreateWithoutInteractionInput>
}

export type AttachmentUpdateWithWhereUniqueWithoutInteractionInput = {
  where: Prisma.AttachmentWhereUniqueInput
  data: Prisma.XOR<Prisma.AttachmentUpdateWithoutInteractionInput, Prisma.AttachmentUncheckedUpdateWithoutInteractionInput>
}

export type AttachmentUpdateManyWithWhereWithoutInteractionInput = {
  where: Prisma.AttachmentScalarWhereInput
  data: Prisma.XOR<Prisma.AttachmentUpdateManyMutationInput, Prisma.AttachmentUncheckedUpdateManyWithoutInteractionInput>
}

export type AttachmentCreateWithoutTaskInput = {
  id?: string
  userId?: string | null
  fileName: string
  fileType: string
  fileUrl: string
  fileSize?: number | null
  createdAt?: Date | string
  client?: Prisma.ClientCreateNestedOneWithoutAttachmentsInput
  interaction?: Prisma.InteractionCreateNestedOneWithoutAttachmentsInput
  appointment?: Prisma.AppointmentCreateNestedOneWithoutAppointmentDocsInput
}

export type AttachmentUncheckedCreateWithoutTaskInput = {
  id?: string
  userId?: string | null
  clientId?: string | null
  interactionId?: string | null
  appointmentId?: string | null
  fileName: string
  fileType: string
  fileUrl: string
  fileSize?: number | null
  createdAt?: Date | string
}

export type AttachmentCreateOrConnectWithoutTaskInput = {
  where: Prisma.AttachmentWhereUniqueInput
  create: Prisma.XOR<Prisma.AttachmentCreateWithoutTaskInput, Prisma.AttachmentUncheckedCreateWithoutTaskInput>
}

export type AttachmentCreateManyTaskInputEnvelope = {
  data: Prisma.AttachmentCreateManyTaskInput | Prisma.AttachmentCreateManyTaskInput[]
  skipDuplicates?: boolean
}

export type AttachmentUpsertWithWhereUniqueWithoutTaskInput = {
  where: Prisma.AttachmentWhereUniqueInput
  update: Prisma.XOR<Prisma.AttachmentUpdateWithoutTaskInput, Prisma.AttachmentUncheckedUpdateWithoutTaskInput>
  create: Prisma.XOR<Prisma.AttachmentCreateWithoutTaskInput, Prisma.AttachmentUncheckedCreateWithoutTaskInput>
}

export type AttachmentUpdateWithWhereUniqueWithoutTaskInput = {
  where: Prisma.AttachmentWhereUniqueInput
  data: Prisma.XOR<Prisma.AttachmentUpdateWithoutTaskInput, Prisma.AttachmentUncheckedUpdateWithoutTaskInput>
}

export type AttachmentUpdateManyWithWhereWithoutTaskInput = {
  where: Prisma.AttachmentScalarWhereInput
  data: Prisma.XOR<Prisma.AttachmentUpdateManyMutationInput, Prisma.AttachmentUncheckedUpdateManyWithoutTaskInput>
}

export type AttachmentCreateManyClientInput = {
  id?: string
  userId?: string | null
  interactionId?: string | null
  taskId?: string | null
  appointmentId?: string | null
  fileName: string
  fileType: string
  fileUrl: string
  fileSize?: number | null
  createdAt?: Date | string
}

export type AttachmentUpdateWithoutClientInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  interaction?: Prisma.InteractionUpdateOneWithoutAttachmentsNestedInput
  task?: Prisma.TaskUpdateOneWithoutAttachmentsNestedInput
  appointment?: Prisma.AppointmentUpdateOneWithoutAppointmentDocsNestedInput
}

export type AttachmentUncheckedUpdateWithoutClientInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  taskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  appointmentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AttachmentUncheckedUpdateManyWithoutClientInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  taskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  appointmentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AttachmentCreateManyAppointmentInput = {
  id?: string
  userId?: string | null
  clientId?: string | null
  interactionId?: string | null
  taskId?: string | null
  fileName: string
  fileType: string
  fileUrl: string
  fileSize?: number | null
  createdAt?: Date | string
}

export type AttachmentUpdateWithoutAppointmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  client?: Prisma.ClientUpdateOneWithoutAttachmentsNestedInput
  interaction?: Prisma.InteractionUpdateOneWithoutAttachmentsNestedInput
  task?: Prisma.TaskUpdateOneWithoutAttachmentsNestedInput
}

export type AttachmentUncheckedUpdateWithoutAppointmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  taskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AttachmentUncheckedUpdateManyWithoutAppointmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  taskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AttachmentCreateManyInteractionInput = {
  id?: string
  userId?: string | null
  clientId?: string | null
  taskId?: string | null
  appointmentId?: string | null
  fileName: string
  fileType: string
  fileUrl: string
  fileSize?: number | null
  createdAt?: Date | string
}

export type AttachmentUpdateWithoutInteractionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  client?: Prisma.ClientUpdateOneWithoutAttachmentsNestedInput
  task?: Prisma.TaskUpdateOneWithoutAttachmentsNestedInput
  appointment?: Prisma.AppointmentUpdateOneWithoutAppointmentDocsNestedInput
}

export type AttachmentUncheckedUpdateWithoutInteractionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  taskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  appointmentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AttachmentUncheckedUpdateManyWithoutInteractionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  taskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  appointmentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AttachmentCreateManyTaskInput = {
  id?: string
  userId?: string | null
  clientId?: string | null
  interactionId?: string | null
  appointmentId?: string | null
  fileName: string
  fileType: string
  fileUrl: string
  fileSize?: number | null
  createdAt?: Date | string
}

export type AttachmentUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  client?: Prisma.ClientUpdateOneWithoutAttachmentsNestedInput
  interaction?: Prisma.InteractionUpdateOneWithoutAttachmentsNestedInput
  appointment?: Prisma.AppointmentUpdateOneWithoutAppointmentDocsNestedInput
}

export type AttachmentUncheckedUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  appointmentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AttachmentUncheckedUpdateManyWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  appointmentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  fileType?: Prisma.StringFieldUpdateOperationsInput | string
  fileUrl?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AttachmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  clientId?: boolean
  interactionId?: boolean
  taskId?: boolean
  appointmentId?: boolean
  fileName?: boolean
  fileType?: boolean
  fileUrl?: boolean
  fileSize?: boolean
  createdAt?: boolean
  client?: boolean | Prisma.Attachment$clientArgs<ExtArgs>
  interaction?: boolean | Prisma.Attachment$interactionArgs<ExtArgs>
  task?: boolean | Prisma.Attachment$taskArgs<ExtArgs>
  appointment?: boolean | Prisma.Attachment$appointmentArgs<ExtArgs>
}, ExtArgs["result"]["attachment"]>

export type AttachmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  clientId?: boolean
  interactionId?: boolean
  taskId?: boolean
  appointmentId?: boolean
  fileName?: boolean
  fileType?: boolean
  fileUrl?: boolean
  fileSize?: boolean
  createdAt?: boolean
  client?: boolean | Prisma.Attachment$clientArgs<ExtArgs>
  interaction?: boolean | Prisma.Attachment$interactionArgs<ExtArgs>
  task?: boolean | Prisma.Attachment$taskArgs<ExtArgs>
  appointment?: boolean | Prisma.Attachment$appointmentArgs<ExtArgs>
}, ExtArgs["result"]["attachment"]>

export type AttachmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  clientId?: boolean
  interactionId?: boolean
  taskId?: boolean
  appointmentId?: boolean
  fileName?: boolean
  fileType?: boolean
  fileUrl?: boolean
  fileSize?: boolean
  createdAt?: boolean
  client?: boolean | Prisma.Attachment$clientArgs<ExtArgs>
  interaction?: boolean | Prisma.Attachment$interactionArgs<ExtArgs>
  task?: boolean | Prisma.Attachment$taskArgs<ExtArgs>
  appointment?: boolean | Prisma.Attachment$appointmentArgs<ExtArgs>
}, ExtArgs["result"]["attachment"]>

export type AttachmentSelectScalar = {
  id?: boolean
  userId?: boolean
  clientId?: boolean
  interactionId?: boolean
  taskId?: boolean
  appointmentId?: boolean
  fileName?: boolean
  fileType?: boolean
  fileUrl?: boolean
  fileSize?: boolean
  createdAt?: boolean
}

export type AttachmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "clientId" | "interactionId" | "taskId" | "appointmentId" | "fileName" | "fileType" | "fileUrl" | "fileSize" | "createdAt", ExtArgs["result"]["attachment"]>
export type AttachmentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  client?: boolean | Prisma.Attachment$clientArgs<ExtArgs>
  interaction?: boolean | Prisma.Attachment$interactionArgs<ExtArgs>
  task?: boolean | Prisma.Attachment$taskArgs<ExtArgs>
  appointment?: boolean | Prisma.Attachment$appointmentArgs<ExtArgs>
}
export type AttachmentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  client?: boolean | Prisma.Attachment$clientArgs<ExtArgs>
  interaction?: boolean | Prisma.Attachment$interactionArgs<ExtArgs>
  task?: boolean | Prisma.Attachment$taskArgs<ExtArgs>
  appointment?: boolean | Prisma.Attachment$appointmentArgs<ExtArgs>
}
export type AttachmentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  client?: boolean | Prisma.Attachment$clientArgs<ExtArgs>
  interaction?: boolean | Prisma.Attachment$interactionArgs<ExtArgs>
  task?: boolean | Prisma.Attachment$taskArgs<ExtArgs>
  appointment?: boolean | Prisma.Attachment$appointmentArgs<ExtArgs>
}

export type $AttachmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Attachment"
  objects: {
    client: Prisma.$ClientPayload<ExtArgs> | null
    interaction: Prisma.$InteractionPayload<ExtArgs> | null
    task: Prisma.$TaskPayload<ExtArgs> | null
    appointment: Prisma.$AppointmentPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string | null
    clientId: string | null
    interactionId: string | null
    taskId: string | null
    appointmentId: string | null
    fileName: string
    fileType: string
    fileUrl: string
    fileSize: number | null
    createdAt: Date
  }, ExtArgs["result"]["attachment"]>
  composites: {}
}

export type AttachmentGetPayload<S extends boolean | null | undefined | AttachmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AttachmentPayload, S>

export type AttachmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AttachmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AttachmentCountAggregateInputType | true
  }

export interface AttachmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Attachment'], meta: { name: 'Attachment' } }
  /**
   * Find zero or one Attachment that matches the filter.
   * @param {AttachmentFindUniqueArgs} args - Arguments to find a Attachment
   * @example
   * // Get one Attachment
   * const attachment = await prisma.attachment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AttachmentFindUniqueArgs>(args: Prisma.SelectSubset<T, AttachmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AttachmentClient<runtime.Types.Result.GetResult<Prisma.$AttachmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Attachment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AttachmentFindUniqueOrThrowArgs} args - Arguments to find a Attachment
   * @example
   * // Get one Attachment
   * const attachment = await prisma.attachment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AttachmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AttachmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AttachmentClient<runtime.Types.Result.GetResult<Prisma.$AttachmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Attachment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttachmentFindFirstArgs} args - Arguments to find a Attachment
   * @example
   * // Get one Attachment
   * const attachment = await prisma.attachment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AttachmentFindFirstArgs>(args?: Prisma.SelectSubset<T, AttachmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__AttachmentClient<runtime.Types.Result.GetResult<Prisma.$AttachmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Attachment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttachmentFindFirstOrThrowArgs} args - Arguments to find a Attachment
   * @example
   * // Get one Attachment
   * const attachment = await prisma.attachment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AttachmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AttachmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AttachmentClient<runtime.Types.Result.GetResult<Prisma.$AttachmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Attachments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttachmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Attachments
   * const attachments = await prisma.attachment.findMany()
   * 
   * // Get first 10 Attachments
   * const attachments = await prisma.attachment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const attachmentWithIdOnly = await prisma.attachment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AttachmentFindManyArgs>(args?: Prisma.SelectSubset<T, AttachmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttachmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Attachment.
   * @param {AttachmentCreateArgs} args - Arguments to create a Attachment.
   * @example
   * // Create one Attachment
   * const Attachment = await prisma.attachment.create({
   *   data: {
   *     // ... data to create a Attachment
   *   }
   * })
   * 
   */
  create<T extends AttachmentCreateArgs>(args: Prisma.SelectSubset<T, AttachmentCreateArgs<ExtArgs>>): Prisma.Prisma__AttachmentClient<runtime.Types.Result.GetResult<Prisma.$AttachmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Attachments.
   * @param {AttachmentCreateManyArgs} args - Arguments to create many Attachments.
   * @example
   * // Create many Attachments
   * const attachment = await prisma.attachment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AttachmentCreateManyArgs>(args?: Prisma.SelectSubset<T, AttachmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Attachments and returns the data saved in the database.
   * @param {AttachmentCreateManyAndReturnArgs} args - Arguments to create many Attachments.
   * @example
   * // Create many Attachments
   * const attachment = await prisma.attachment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Attachments and only return the `id`
   * const attachmentWithIdOnly = await prisma.attachment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AttachmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AttachmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttachmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Attachment.
   * @param {AttachmentDeleteArgs} args - Arguments to delete one Attachment.
   * @example
   * // Delete one Attachment
   * const Attachment = await prisma.attachment.delete({
   *   where: {
   *     // ... filter to delete one Attachment
   *   }
   * })
   * 
   */
  delete<T extends AttachmentDeleteArgs>(args: Prisma.SelectSubset<T, AttachmentDeleteArgs<ExtArgs>>): Prisma.Prisma__AttachmentClient<runtime.Types.Result.GetResult<Prisma.$AttachmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Attachment.
   * @param {AttachmentUpdateArgs} args - Arguments to update one Attachment.
   * @example
   * // Update one Attachment
   * const attachment = await prisma.attachment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AttachmentUpdateArgs>(args: Prisma.SelectSubset<T, AttachmentUpdateArgs<ExtArgs>>): Prisma.Prisma__AttachmentClient<runtime.Types.Result.GetResult<Prisma.$AttachmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Attachments.
   * @param {AttachmentDeleteManyArgs} args - Arguments to filter Attachments to delete.
   * @example
   * // Delete a few Attachments
   * const { count } = await prisma.attachment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AttachmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, AttachmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Attachments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttachmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Attachments
   * const attachment = await prisma.attachment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AttachmentUpdateManyArgs>(args: Prisma.SelectSubset<T, AttachmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Attachments and returns the data updated in the database.
   * @param {AttachmentUpdateManyAndReturnArgs} args - Arguments to update many Attachments.
   * @example
   * // Update many Attachments
   * const attachment = await prisma.attachment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Attachments and only return the `id`
   * const attachmentWithIdOnly = await prisma.attachment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AttachmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AttachmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttachmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Attachment.
   * @param {AttachmentUpsertArgs} args - Arguments to update or create a Attachment.
   * @example
   * // Update or create a Attachment
   * const attachment = await prisma.attachment.upsert({
   *   create: {
   *     // ... data to create a Attachment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Attachment we want to update
   *   }
   * })
   */
  upsert<T extends AttachmentUpsertArgs>(args: Prisma.SelectSubset<T, AttachmentUpsertArgs<ExtArgs>>): Prisma.Prisma__AttachmentClient<runtime.Types.Result.GetResult<Prisma.$AttachmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Attachments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttachmentCountArgs} args - Arguments to filter Attachments to count.
   * @example
   * // Count the number of Attachments
   * const count = await prisma.attachment.count({
   *   where: {
   *     // ... the filter for the Attachments we want to count
   *   }
   * })
  **/
  count<T extends AttachmentCountArgs>(
    args?: Prisma.Subset<T, AttachmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AttachmentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Attachment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttachmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AttachmentAggregateArgs>(args: Prisma.Subset<T, AttachmentAggregateArgs>): Prisma.PrismaPromise<GetAttachmentAggregateType<T>>

  /**
   * Group by Attachment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AttachmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AttachmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AttachmentGroupByArgs['orderBy'] }
      : { orderBy?: AttachmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AttachmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAttachmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Attachment model
 */
readonly fields: AttachmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Attachment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AttachmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  client<T extends Prisma.Attachment$clientArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Attachment$clientArgs<ExtArgs>>): Prisma.Prisma__ClientClient<runtime.Types.Result.GetResult<Prisma.$ClientPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  interaction<T extends Prisma.Attachment$interactionArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Attachment$interactionArgs<ExtArgs>>): Prisma.Prisma__InteractionClient<runtime.Types.Result.GetResult<Prisma.$InteractionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  task<T extends Prisma.Attachment$taskArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Attachment$taskArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  appointment<T extends Prisma.Attachment$appointmentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Attachment$appointmentArgs<ExtArgs>>): Prisma.Prisma__AppointmentClient<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Attachment model
 */
export interface AttachmentFieldRefs {
  readonly id: Prisma.FieldRef<"Attachment", 'String'>
  readonly userId: Prisma.FieldRef<"Attachment", 'String'>
  readonly clientId: Prisma.FieldRef<"Attachment", 'String'>
  readonly interactionId: Prisma.FieldRef<"Attachment", 'String'>
  readonly taskId: Prisma.FieldRef<"Attachment", 'String'>
  readonly appointmentId: Prisma.FieldRef<"Attachment", 'String'>
  readonly fileName: Prisma.FieldRef<"Attachment", 'String'>
  readonly fileType: Prisma.FieldRef<"Attachment", 'String'>
  readonly fileUrl: Prisma.FieldRef<"Attachment", 'String'>
  readonly fileSize: Prisma.FieldRef<"Attachment", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Attachment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Attachment findUnique
 */
export type AttachmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attachment
   */
  select?: Prisma.AttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Attachment
   */
  omit?: Prisma.AttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttachmentInclude<ExtArgs> | null
  /**
   * Filter, which Attachment to fetch.
   */
  where: Prisma.AttachmentWhereUniqueInput
}

/**
 * Attachment findUniqueOrThrow
 */
export type AttachmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attachment
   */
  select?: Prisma.AttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Attachment
   */
  omit?: Prisma.AttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttachmentInclude<ExtArgs> | null
  /**
   * Filter, which Attachment to fetch.
   */
  where: Prisma.AttachmentWhereUniqueInput
}

/**
 * Attachment findFirst
 */
export type AttachmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attachment
   */
  select?: Prisma.AttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Attachment
   */
  omit?: Prisma.AttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttachmentInclude<ExtArgs> | null
  /**
   * Filter, which Attachment to fetch.
   */
  where?: Prisma.AttachmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Attachments to fetch.
   */
  orderBy?: Prisma.AttachmentOrderByWithRelationInput | Prisma.AttachmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Attachments.
   */
  cursor?: Prisma.AttachmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Attachments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Attachments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Attachments.
   */
  distinct?: Prisma.AttachmentScalarFieldEnum | Prisma.AttachmentScalarFieldEnum[]
}

/**
 * Attachment findFirstOrThrow
 */
export type AttachmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attachment
   */
  select?: Prisma.AttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Attachment
   */
  omit?: Prisma.AttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttachmentInclude<ExtArgs> | null
  /**
   * Filter, which Attachment to fetch.
   */
  where?: Prisma.AttachmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Attachments to fetch.
   */
  orderBy?: Prisma.AttachmentOrderByWithRelationInput | Prisma.AttachmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Attachments.
   */
  cursor?: Prisma.AttachmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Attachments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Attachments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Attachments.
   */
  distinct?: Prisma.AttachmentScalarFieldEnum | Prisma.AttachmentScalarFieldEnum[]
}

/**
 * Attachment findMany
 */
export type AttachmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attachment
   */
  select?: Prisma.AttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Attachment
   */
  omit?: Prisma.AttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttachmentInclude<ExtArgs> | null
  /**
   * Filter, which Attachments to fetch.
   */
  where?: Prisma.AttachmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Attachments to fetch.
   */
  orderBy?: Prisma.AttachmentOrderByWithRelationInput | Prisma.AttachmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Attachments.
   */
  cursor?: Prisma.AttachmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Attachments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Attachments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Attachments.
   */
  distinct?: Prisma.AttachmentScalarFieldEnum | Prisma.AttachmentScalarFieldEnum[]
}

/**
 * Attachment create
 */
export type AttachmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attachment
   */
  select?: Prisma.AttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Attachment
   */
  omit?: Prisma.AttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttachmentInclude<ExtArgs> | null
  /**
   * The data needed to create a Attachment.
   */
  data: Prisma.XOR<Prisma.AttachmentCreateInput, Prisma.AttachmentUncheckedCreateInput>
}

/**
 * Attachment createMany
 */
export type AttachmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Attachments.
   */
  data: Prisma.AttachmentCreateManyInput | Prisma.AttachmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Attachment createManyAndReturn
 */
export type AttachmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attachment
   */
  select?: Prisma.AttachmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Attachment
   */
  omit?: Prisma.AttachmentOmit<ExtArgs> | null
  /**
   * The data used to create many Attachments.
   */
  data: Prisma.AttachmentCreateManyInput | Prisma.AttachmentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttachmentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Attachment update
 */
export type AttachmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attachment
   */
  select?: Prisma.AttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Attachment
   */
  omit?: Prisma.AttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttachmentInclude<ExtArgs> | null
  /**
   * The data needed to update a Attachment.
   */
  data: Prisma.XOR<Prisma.AttachmentUpdateInput, Prisma.AttachmentUncheckedUpdateInput>
  /**
   * Choose, which Attachment to update.
   */
  where: Prisma.AttachmentWhereUniqueInput
}

/**
 * Attachment updateMany
 */
export type AttachmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Attachments.
   */
  data: Prisma.XOR<Prisma.AttachmentUpdateManyMutationInput, Prisma.AttachmentUncheckedUpdateManyInput>
  /**
   * Filter which Attachments to update
   */
  where?: Prisma.AttachmentWhereInput
  /**
   * Limit how many Attachments to update.
   */
  limit?: number
}

/**
 * Attachment updateManyAndReturn
 */
export type AttachmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attachment
   */
  select?: Prisma.AttachmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Attachment
   */
  omit?: Prisma.AttachmentOmit<ExtArgs> | null
  /**
   * The data used to update Attachments.
   */
  data: Prisma.XOR<Prisma.AttachmentUpdateManyMutationInput, Prisma.AttachmentUncheckedUpdateManyInput>
  /**
   * Filter which Attachments to update
   */
  where?: Prisma.AttachmentWhereInput
  /**
   * Limit how many Attachments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttachmentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Attachment upsert
 */
export type AttachmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attachment
   */
  select?: Prisma.AttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Attachment
   */
  omit?: Prisma.AttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttachmentInclude<ExtArgs> | null
  /**
   * The filter to search for the Attachment to update in case it exists.
   */
  where: Prisma.AttachmentWhereUniqueInput
  /**
   * In case the Attachment found by the `where` argument doesn't exist, create a new Attachment with this data.
   */
  create: Prisma.XOR<Prisma.AttachmentCreateInput, Prisma.AttachmentUncheckedCreateInput>
  /**
   * In case the Attachment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AttachmentUpdateInput, Prisma.AttachmentUncheckedUpdateInput>
}

/**
 * Attachment delete
 */
export type AttachmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attachment
   */
  select?: Prisma.AttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Attachment
   */
  omit?: Prisma.AttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttachmentInclude<ExtArgs> | null
  /**
   * Filter which Attachment to delete.
   */
  where: Prisma.AttachmentWhereUniqueInput
}

/**
 * Attachment deleteMany
 */
export type AttachmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Attachments to delete
   */
  where?: Prisma.AttachmentWhereInput
  /**
   * Limit how many Attachments to delete.
   */
  limit?: number
}

/**
 * Attachment.client
 */
export type Attachment$clientArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Client
   */
  select?: Prisma.ClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Client
   */
  omit?: Prisma.ClientOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientInclude<ExtArgs> | null
  where?: Prisma.ClientWhereInput
}

/**
 * Attachment.interaction
 */
export type Attachment$interactionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interaction
   */
  select?: Prisma.InteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interaction
   */
  omit?: Prisma.InteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionInclude<ExtArgs> | null
  where?: Prisma.InteractionWhereInput
}

/**
 * Attachment.task
 */
export type Attachment$taskArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskInclude<ExtArgs> | null
  where?: Prisma.TaskWhereInput
}

/**
 * Attachment.appointment
 */
export type Attachment$appointmentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentInclude<ExtArgs> | null
  where?: Prisma.AppointmentWhereInput
}

/**
 * Attachment without action
 */
export type AttachmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attachment
   */
  select?: Prisma.AttachmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Attachment
   */
  omit?: Prisma.AttachmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttachmentInclude<ExtArgs> | null
}
