
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ConsultantTag` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ConsultantTag
 * 
 */
export type ConsultantTagModel = runtime.Types.Result.DefaultSelection<Prisma.$ConsultantTagPayload>

export type AggregateConsultantTag = {
  _count: ConsultantTagCountAggregateOutputType | null
  _min: ConsultantTagMinAggregateOutputType | null
  _max: ConsultantTagMaxAggregateOutputType | null
}

export type ConsultantTagMinAggregateOutputType = {
  id: string | null
  name: string | null
}

export type ConsultantTagMaxAggregateOutputType = {
  id: string | null
  name: string | null
}

export type ConsultantTagCountAggregateOutputType = {
  id: number
  name: number
  _all: number
}


export type ConsultantTagMinAggregateInputType = {
  id?: true
  name?: true
}

export type ConsultantTagMaxAggregateInputType = {
  id?: true
  name?: true
}

export type ConsultantTagCountAggregateInputType = {
  id?: true
  name?: true
  _all?: true
}

export type ConsultantTagAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ConsultantTag to aggregate.
   */
  where?: Prisma.ConsultantTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConsultantTags to fetch.
   */
  orderBy?: Prisma.ConsultantTagOrderByWithRelationInput | Prisma.ConsultantTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ConsultantTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConsultantTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConsultantTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ConsultantTags
  **/
  _count?: true | ConsultantTagCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ConsultantTagMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ConsultantTagMaxAggregateInputType
}

export type GetConsultantTagAggregateType<T extends ConsultantTagAggregateArgs> = {
      [P in keyof T & keyof AggregateConsultantTag]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateConsultantTag[P]>
    : Prisma.GetScalarType<T[P], AggregateConsultantTag[P]>
}




export type ConsultantTagGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ConsultantTagWhereInput
  orderBy?: Prisma.ConsultantTagOrderByWithAggregationInput | Prisma.ConsultantTagOrderByWithAggregationInput[]
  by: Prisma.ConsultantTagScalarFieldEnum[] | Prisma.ConsultantTagScalarFieldEnum
  having?: Prisma.ConsultantTagScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ConsultantTagCountAggregateInputType | true
  _min?: ConsultantTagMinAggregateInputType
  _max?: ConsultantTagMaxAggregateInputType
}

export type ConsultantTagGroupByOutputType = {
  id: string
  name: string
  _count: ConsultantTagCountAggregateOutputType | null
  _min: ConsultantTagMinAggregateOutputType | null
  _max: ConsultantTagMaxAggregateOutputType | null
}

export type GetConsultantTagGroupByPayload<T extends ConsultantTagGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ConsultantTagGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ConsultantTagGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ConsultantTagGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ConsultantTagGroupByOutputType[P]>
      }
    >
  >



export type ConsultantTagWhereInput = {
  AND?: Prisma.ConsultantTagWhereInput | Prisma.ConsultantTagWhereInput[]
  OR?: Prisma.ConsultantTagWhereInput[]
  NOT?: Prisma.ConsultantTagWhereInput | Prisma.ConsultantTagWhereInput[]
  id?: Prisma.StringFilter<"ConsultantTag"> | string
  name?: Prisma.StringFilter<"ConsultantTag"> | string
  users?: Prisma.UserListRelationFilter
}

export type ConsultantTagOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  users?: Prisma.UserOrderByRelationAggregateInput
}

export type ConsultantTagWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.ConsultantTagWhereInput | Prisma.ConsultantTagWhereInput[]
  OR?: Prisma.ConsultantTagWhereInput[]
  NOT?: Prisma.ConsultantTagWhereInput | Prisma.ConsultantTagWhereInput[]
  users?: Prisma.UserListRelationFilter
}, "id" | "name">

export type ConsultantTagOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  _count?: Prisma.ConsultantTagCountOrderByAggregateInput
  _max?: Prisma.ConsultantTagMaxOrderByAggregateInput
  _min?: Prisma.ConsultantTagMinOrderByAggregateInput
}

export type ConsultantTagScalarWhereWithAggregatesInput = {
  AND?: Prisma.ConsultantTagScalarWhereWithAggregatesInput | Prisma.ConsultantTagScalarWhereWithAggregatesInput[]
  OR?: Prisma.ConsultantTagScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ConsultantTagScalarWhereWithAggregatesInput | Prisma.ConsultantTagScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ConsultantTag"> | string
  name?: Prisma.StringWithAggregatesFilter<"ConsultantTag"> | string
}

export type ConsultantTagCreateInput = {
  id?: string
  name: string
  users?: Prisma.UserCreateNestedManyWithoutConsultantTagsInput
}

export type ConsultantTagUncheckedCreateInput = {
  id?: string
  name: string
  users?: Prisma.UserUncheckedCreateNestedManyWithoutConsultantTagsInput
}

export type ConsultantTagUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  users?: Prisma.UserUpdateManyWithoutConsultantTagsNestedInput
}

export type ConsultantTagUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  users?: Prisma.UserUncheckedUpdateManyWithoutConsultantTagsNestedInput
}

export type ConsultantTagCreateManyInput = {
  id?: string
  name: string
}

export type ConsultantTagUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ConsultantTagUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ConsultantTagCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type ConsultantTagMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type ConsultantTagMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type ConsultantTagListRelationFilter = {
  every?: Prisma.ConsultantTagWhereInput
  some?: Prisma.ConsultantTagWhereInput
  none?: Prisma.ConsultantTagWhereInput
}

export type ConsultantTagOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type ConsultantTagCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.ConsultantTagCreateWithoutUsersInput, Prisma.ConsultantTagUncheckedCreateWithoutUsersInput> | Prisma.ConsultantTagCreateWithoutUsersInput[] | Prisma.ConsultantTagUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.ConsultantTagCreateOrConnectWithoutUsersInput | Prisma.ConsultantTagCreateOrConnectWithoutUsersInput[]
  connect?: Prisma.ConsultantTagWhereUniqueInput | Prisma.ConsultantTagWhereUniqueInput[]
}

export type ConsultantTagUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.ConsultantTagCreateWithoutUsersInput, Prisma.ConsultantTagUncheckedCreateWithoutUsersInput> | Prisma.ConsultantTagCreateWithoutUsersInput[] | Prisma.ConsultantTagUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.ConsultantTagCreateOrConnectWithoutUsersInput | Prisma.ConsultantTagCreateOrConnectWithoutUsersInput[]
  connect?: Prisma.ConsultantTagWhereUniqueInput | Prisma.ConsultantTagWhereUniqueInput[]
}

export type ConsultantTagUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.ConsultantTagCreateWithoutUsersInput, Prisma.ConsultantTagUncheckedCreateWithoutUsersInput> | Prisma.ConsultantTagCreateWithoutUsersInput[] | Prisma.ConsultantTagUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.ConsultantTagCreateOrConnectWithoutUsersInput | Prisma.ConsultantTagCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.ConsultantTagUpsertWithWhereUniqueWithoutUsersInput | Prisma.ConsultantTagUpsertWithWhereUniqueWithoutUsersInput[]
  set?: Prisma.ConsultantTagWhereUniqueInput | Prisma.ConsultantTagWhereUniqueInput[]
  disconnect?: Prisma.ConsultantTagWhereUniqueInput | Prisma.ConsultantTagWhereUniqueInput[]
  delete?: Prisma.ConsultantTagWhereUniqueInput | Prisma.ConsultantTagWhereUniqueInput[]
  connect?: Prisma.ConsultantTagWhereUniqueInput | Prisma.ConsultantTagWhereUniqueInput[]
  update?: Prisma.ConsultantTagUpdateWithWhereUniqueWithoutUsersInput | Prisma.ConsultantTagUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.ConsultantTagUpdateManyWithWhereWithoutUsersInput | Prisma.ConsultantTagUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.ConsultantTagScalarWhereInput | Prisma.ConsultantTagScalarWhereInput[]
}

export type ConsultantTagUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.ConsultantTagCreateWithoutUsersInput, Prisma.ConsultantTagUncheckedCreateWithoutUsersInput> | Prisma.ConsultantTagCreateWithoutUsersInput[] | Prisma.ConsultantTagUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.ConsultantTagCreateOrConnectWithoutUsersInput | Prisma.ConsultantTagCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.ConsultantTagUpsertWithWhereUniqueWithoutUsersInput | Prisma.ConsultantTagUpsertWithWhereUniqueWithoutUsersInput[]
  set?: Prisma.ConsultantTagWhereUniqueInput | Prisma.ConsultantTagWhereUniqueInput[]
  disconnect?: Prisma.ConsultantTagWhereUniqueInput | Prisma.ConsultantTagWhereUniqueInput[]
  delete?: Prisma.ConsultantTagWhereUniqueInput | Prisma.ConsultantTagWhereUniqueInput[]
  connect?: Prisma.ConsultantTagWhereUniqueInput | Prisma.ConsultantTagWhereUniqueInput[]
  update?: Prisma.ConsultantTagUpdateWithWhereUniqueWithoutUsersInput | Prisma.ConsultantTagUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.ConsultantTagUpdateManyWithWhereWithoutUsersInput | Prisma.ConsultantTagUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.ConsultantTagScalarWhereInput | Prisma.ConsultantTagScalarWhereInput[]
}

export type ConsultantTagCreateWithoutUsersInput = {
  id?: string
  name: string
}

export type ConsultantTagUncheckedCreateWithoutUsersInput = {
  id?: string
  name: string
}

export type ConsultantTagCreateOrConnectWithoutUsersInput = {
  where: Prisma.ConsultantTagWhereUniqueInput
  create: Prisma.XOR<Prisma.ConsultantTagCreateWithoutUsersInput, Prisma.ConsultantTagUncheckedCreateWithoutUsersInput>
}

export type ConsultantTagUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.ConsultantTagWhereUniqueInput
  update: Prisma.XOR<Prisma.ConsultantTagUpdateWithoutUsersInput, Prisma.ConsultantTagUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.ConsultantTagCreateWithoutUsersInput, Prisma.ConsultantTagUncheckedCreateWithoutUsersInput>
}

export type ConsultantTagUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.ConsultantTagWhereUniqueInput
  data: Prisma.XOR<Prisma.ConsultantTagUpdateWithoutUsersInput, Prisma.ConsultantTagUncheckedUpdateWithoutUsersInput>
}

export type ConsultantTagUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.ConsultantTagScalarWhereInput
  data: Prisma.XOR<Prisma.ConsultantTagUpdateManyMutationInput, Prisma.ConsultantTagUncheckedUpdateManyWithoutUsersInput>
}

export type ConsultantTagScalarWhereInput = {
  AND?: Prisma.ConsultantTagScalarWhereInput | Prisma.ConsultantTagScalarWhereInput[]
  OR?: Prisma.ConsultantTagScalarWhereInput[]
  NOT?: Prisma.ConsultantTagScalarWhereInput | Prisma.ConsultantTagScalarWhereInput[]
  id?: Prisma.StringFilter<"ConsultantTag"> | string
  name?: Prisma.StringFilter<"ConsultantTag"> | string
}

export type ConsultantTagUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ConsultantTagUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ConsultantTagUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type ConsultantTagCountOutputType
 */

export type ConsultantTagCountOutputType = {
  users: number
}

export type ConsultantTagCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | ConsultantTagCountOutputTypeCountUsersArgs
}

/**
 * ConsultantTagCountOutputType without action
 */
export type ConsultantTagCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConsultantTagCountOutputType
   */
  select?: Prisma.ConsultantTagCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ConsultantTagCountOutputType without action
 */
export type ConsultantTagCountOutputTypeCountUsersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWhereInput
}


export type ConsultantTagSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  users?: boolean | Prisma.ConsultantTag$usersArgs<ExtArgs>
  _count?: boolean | Prisma.ConsultantTagCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["consultantTag"]>

export type ConsultantTagSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["consultantTag"]>

export type ConsultantTagSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["consultantTag"]>

export type ConsultantTagSelectScalar = {
  id?: boolean
  name?: boolean
}

export type ConsultantTagOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name", ExtArgs["result"]["consultantTag"]>
export type ConsultantTagInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  users?: boolean | Prisma.ConsultantTag$usersArgs<ExtArgs>
  _count?: boolean | Prisma.ConsultantTagCountOutputTypeDefaultArgs<ExtArgs>
}
export type ConsultantTagIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ConsultantTagIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ConsultantTagPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ConsultantTag"
  objects: {
    users: Prisma.$UserPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
  }, ExtArgs["result"]["consultantTag"]>
  composites: {}
}

export type ConsultantTagGetPayload<S extends boolean | null | undefined | ConsultantTagDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ConsultantTagPayload, S>

export type ConsultantTagCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ConsultantTagFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ConsultantTagCountAggregateInputType | true
  }

export interface ConsultantTagDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ConsultantTag'], meta: { name: 'ConsultantTag' } }
  /**
   * Find zero or one ConsultantTag that matches the filter.
   * @param {ConsultantTagFindUniqueArgs} args - Arguments to find a ConsultantTag
   * @example
   * // Get one ConsultantTag
   * const consultantTag = await prisma.consultantTag.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ConsultantTagFindUniqueArgs>(args: Prisma.SelectSubset<T, ConsultantTagFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ConsultantTagClient<runtime.Types.Result.GetResult<Prisma.$ConsultantTagPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ConsultantTag that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ConsultantTagFindUniqueOrThrowArgs} args - Arguments to find a ConsultantTag
   * @example
   * // Get one ConsultantTag
   * const consultantTag = await prisma.consultantTag.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ConsultantTagFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ConsultantTagFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ConsultantTagClient<runtime.Types.Result.GetResult<Prisma.$ConsultantTagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ConsultantTag that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsultantTagFindFirstArgs} args - Arguments to find a ConsultantTag
   * @example
   * // Get one ConsultantTag
   * const consultantTag = await prisma.consultantTag.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ConsultantTagFindFirstArgs>(args?: Prisma.SelectSubset<T, ConsultantTagFindFirstArgs<ExtArgs>>): Prisma.Prisma__ConsultantTagClient<runtime.Types.Result.GetResult<Prisma.$ConsultantTagPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ConsultantTag that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsultantTagFindFirstOrThrowArgs} args - Arguments to find a ConsultantTag
   * @example
   * // Get one ConsultantTag
   * const consultantTag = await prisma.consultantTag.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ConsultantTagFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ConsultantTagFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ConsultantTagClient<runtime.Types.Result.GetResult<Prisma.$ConsultantTagPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ConsultantTags that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsultantTagFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ConsultantTags
   * const consultantTags = await prisma.consultantTag.findMany()
   * 
   * // Get first 10 ConsultantTags
   * const consultantTags = await prisma.consultantTag.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const consultantTagWithIdOnly = await prisma.consultantTag.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ConsultantTagFindManyArgs>(args?: Prisma.SelectSubset<T, ConsultantTagFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConsultantTagPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ConsultantTag.
   * @param {ConsultantTagCreateArgs} args - Arguments to create a ConsultantTag.
   * @example
   * // Create one ConsultantTag
   * const ConsultantTag = await prisma.consultantTag.create({
   *   data: {
   *     // ... data to create a ConsultantTag
   *   }
   * })
   * 
   */
  create<T extends ConsultantTagCreateArgs>(args: Prisma.SelectSubset<T, ConsultantTagCreateArgs<ExtArgs>>): Prisma.Prisma__ConsultantTagClient<runtime.Types.Result.GetResult<Prisma.$ConsultantTagPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ConsultantTags.
   * @param {ConsultantTagCreateManyArgs} args - Arguments to create many ConsultantTags.
   * @example
   * // Create many ConsultantTags
   * const consultantTag = await prisma.consultantTag.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ConsultantTagCreateManyArgs>(args?: Prisma.SelectSubset<T, ConsultantTagCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ConsultantTags and returns the data saved in the database.
   * @param {ConsultantTagCreateManyAndReturnArgs} args - Arguments to create many ConsultantTags.
   * @example
   * // Create many ConsultantTags
   * const consultantTag = await prisma.consultantTag.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ConsultantTags and only return the `id`
   * const consultantTagWithIdOnly = await prisma.consultantTag.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ConsultantTagCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ConsultantTagCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConsultantTagPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ConsultantTag.
   * @param {ConsultantTagDeleteArgs} args - Arguments to delete one ConsultantTag.
   * @example
   * // Delete one ConsultantTag
   * const ConsultantTag = await prisma.consultantTag.delete({
   *   where: {
   *     // ... filter to delete one ConsultantTag
   *   }
   * })
   * 
   */
  delete<T extends ConsultantTagDeleteArgs>(args: Prisma.SelectSubset<T, ConsultantTagDeleteArgs<ExtArgs>>): Prisma.Prisma__ConsultantTagClient<runtime.Types.Result.GetResult<Prisma.$ConsultantTagPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ConsultantTag.
   * @param {ConsultantTagUpdateArgs} args - Arguments to update one ConsultantTag.
   * @example
   * // Update one ConsultantTag
   * const consultantTag = await prisma.consultantTag.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ConsultantTagUpdateArgs>(args: Prisma.SelectSubset<T, ConsultantTagUpdateArgs<ExtArgs>>): Prisma.Prisma__ConsultantTagClient<runtime.Types.Result.GetResult<Prisma.$ConsultantTagPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ConsultantTags.
   * @param {ConsultantTagDeleteManyArgs} args - Arguments to filter ConsultantTags to delete.
   * @example
   * // Delete a few ConsultantTags
   * const { count } = await prisma.consultantTag.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ConsultantTagDeleteManyArgs>(args?: Prisma.SelectSubset<T, ConsultantTagDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ConsultantTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsultantTagUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ConsultantTags
   * const consultantTag = await prisma.consultantTag.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ConsultantTagUpdateManyArgs>(args: Prisma.SelectSubset<T, ConsultantTagUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ConsultantTags and returns the data updated in the database.
   * @param {ConsultantTagUpdateManyAndReturnArgs} args - Arguments to update many ConsultantTags.
   * @example
   * // Update many ConsultantTags
   * const consultantTag = await prisma.consultantTag.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ConsultantTags and only return the `id`
   * const consultantTagWithIdOnly = await prisma.consultantTag.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ConsultantTagUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ConsultantTagUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConsultantTagPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ConsultantTag.
   * @param {ConsultantTagUpsertArgs} args - Arguments to update or create a ConsultantTag.
   * @example
   * // Update or create a ConsultantTag
   * const consultantTag = await prisma.consultantTag.upsert({
   *   create: {
   *     // ... data to create a ConsultantTag
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ConsultantTag we want to update
   *   }
   * })
   */
  upsert<T extends ConsultantTagUpsertArgs>(args: Prisma.SelectSubset<T, ConsultantTagUpsertArgs<ExtArgs>>): Prisma.Prisma__ConsultantTagClient<runtime.Types.Result.GetResult<Prisma.$ConsultantTagPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ConsultantTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsultantTagCountArgs} args - Arguments to filter ConsultantTags to count.
   * @example
   * // Count the number of ConsultantTags
   * const count = await prisma.consultantTag.count({
   *   where: {
   *     // ... the filter for the ConsultantTags we want to count
   *   }
   * })
  **/
  count<T extends ConsultantTagCountArgs>(
    args?: Prisma.Subset<T, ConsultantTagCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ConsultantTagCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ConsultantTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsultantTagAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ConsultantTagAggregateArgs>(args: Prisma.Subset<T, ConsultantTagAggregateArgs>): Prisma.PrismaPromise<GetConsultantTagAggregateType<T>>

  /**
   * Group by ConsultantTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsultantTagGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ConsultantTagGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ConsultantTagGroupByArgs['orderBy'] }
      : { orderBy?: ConsultantTagGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ConsultantTagGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetConsultantTagGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ConsultantTag model
 */
readonly fields: ConsultantTagFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ConsultantTag.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ConsultantTagClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  users<T extends Prisma.ConsultantTag$usersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ConsultantTag$usersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ConsultantTag model
 */
export interface ConsultantTagFieldRefs {
  readonly id: Prisma.FieldRef<"ConsultantTag", 'String'>
  readonly name: Prisma.FieldRef<"ConsultantTag", 'String'>
}
    

// Custom InputTypes
/**
 * ConsultantTag findUnique
 */
export type ConsultantTagFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConsultantTag
   */
  select?: Prisma.ConsultantTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConsultantTag
   */
  omit?: Prisma.ConsultantTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsultantTagInclude<ExtArgs> | null
  /**
   * Filter, which ConsultantTag to fetch.
   */
  where: Prisma.ConsultantTagWhereUniqueInput
}

/**
 * ConsultantTag findUniqueOrThrow
 */
export type ConsultantTagFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConsultantTag
   */
  select?: Prisma.ConsultantTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConsultantTag
   */
  omit?: Prisma.ConsultantTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsultantTagInclude<ExtArgs> | null
  /**
   * Filter, which ConsultantTag to fetch.
   */
  where: Prisma.ConsultantTagWhereUniqueInput
}

/**
 * ConsultantTag findFirst
 */
export type ConsultantTagFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConsultantTag
   */
  select?: Prisma.ConsultantTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConsultantTag
   */
  omit?: Prisma.ConsultantTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsultantTagInclude<ExtArgs> | null
  /**
   * Filter, which ConsultantTag to fetch.
   */
  where?: Prisma.ConsultantTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConsultantTags to fetch.
   */
  orderBy?: Prisma.ConsultantTagOrderByWithRelationInput | Prisma.ConsultantTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ConsultantTags.
   */
  cursor?: Prisma.ConsultantTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConsultantTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConsultantTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ConsultantTags.
   */
  distinct?: Prisma.ConsultantTagScalarFieldEnum | Prisma.ConsultantTagScalarFieldEnum[]
}

/**
 * ConsultantTag findFirstOrThrow
 */
export type ConsultantTagFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConsultantTag
   */
  select?: Prisma.ConsultantTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConsultantTag
   */
  omit?: Prisma.ConsultantTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsultantTagInclude<ExtArgs> | null
  /**
   * Filter, which ConsultantTag to fetch.
   */
  where?: Prisma.ConsultantTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConsultantTags to fetch.
   */
  orderBy?: Prisma.ConsultantTagOrderByWithRelationInput | Prisma.ConsultantTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ConsultantTags.
   */
  cursor?: Prisma.ConsultantTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConsultantTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConsultantTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ConsultantTags.
   */
  distinct?: Prisma.ConsultantTagScalarFieldEnum | Prisma.ConsultantTagScalarFieldEnum[]
}

/**
 * ConsultantTag findMany
 */
export type ConsultantTagFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConsultantTag
   */
  select?: Prisma.ConsultantTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConsultantTag
   */
  omit?: Prisma.ConsultantTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsultantTagInclude<ExtArgs> | null
  /**
   * Filter, which ConsultantTags to fetch.
   */
  where?: Prisma.ConsultantTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ConsultantTags to fetch.
   */
  orderBy?: Prisma.ConsultantTagOrderByWithRelationInput | Prisma.ConsultantTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ConsultantTags.
   */
  cursor?: Prisma.ConsultantTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ConsultantTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ConsultantTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ConsultantTags.
   */
  distinct?: Prisma.ConsultantTagScalarFieldEnum | Prisma.ConsultantTagScalarFieldEnum[]
}

/**
 * ConsultantTag create
 */
export type ConsultantTagCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConsultantTag
   */
  select?: Prisma.ConsultantTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConsultantTag
   */
  omit?: Prisma.ConsultantTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsultantTagInclude<ExtArgs> | null
  /**
   * The data needed to create a ConsultantTag.
   */
  data: Prisma.XOR<Prisma.ConsultantTagCreateInput, Prisma.ConsultantTagUncheckedCreateInput>
}

/**
 * ConsultantTag createMany
 */
export type ConsultantTagCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ConsultantTags.
   */
  data: Prisma.ConsultantTagCreateManyInput | Prisma.ConsultantTagCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ConsultantTag createManyAndReturn
 */
export type ConsultantTagCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConsultantTag
   */
  select?: Prisma.ConsultantTagSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ConsultantTag
   */
  omit?: Prisma.ConsultantTagOmit<ExtArgs> | null
  /**
   * The data used to create many ConsultantTags.
   */
  data: Prisma.ConsultantTagCreateManyInput | Prisma.ConsultantTagCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ConsultantTag update
 */
export type ConsultantTagUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConsultantTag
   */
  select?: Prisma.ConsultantTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConsultantTag
   */
  omit?: Prisma.ConsultantTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsultantTagInclude<ExtArgs> | null
  /**
   * The data needed to update a ConsultantTag.
   */
  data: Prisma.XOR<Prisma.ConsultantTagUpdateInput, Prisma.ConsultantTagUncheckedUpdateInput>
  /**
   * Choose, which ConsultantTag to update.
   */
  where: Prisma.ConsultantTagWhereUniqueInput
}

/**
 * ConsultantTag updateMany
 */
export type ConsultantTagUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ConsultantTags.
   */
  data: Prisma.XOR<Prisma.ConsultantTagUpdateManyMutationInput, Prisma.ConsultantTagUncheckedUpdateManyInput>
  /**
   * Filter which ConsultantTags to update
   */
  where?: Prisma.ConsultantTagWhereInput
  /**
   * Limit how many ConsultantTags to update.
   */
  limit?: number
}

/**
 * ConsultantTag updateManyAndReturn
 */
export type ConsultantTagUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConsultantTag
   */
  select?: Prisma.ConsultantTagSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ConsultantTag
   */
  omit?: Prisma.ConsultantTagOmit<ExtArgs> | null
  /**
   * The data used to update ConsultantTags.
   */
  data: Prisma.XOR<Prisma.ConsultantTagUpdateManyMutationInput, Prisma.ConsultantTagUncheckedUpdateManyInput>
  /**
   * Filter which ConsultantTags to update
   */
  where?: Prisma.ConsultantTagWhereInput
  /**
   * Limit how many ConsultantTags to update.
   */
  limit?: number
}

/**
 * ConsultantTag upsert
 */
export type ConsultantTagUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConsultantTag
   */
  select?: Prisma.ConsultantTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConsultantTag
   */
  omit?: Prisma.ConsultantTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsultantTagInclude<ExtArgs> | null
  /**
   * The filter to search for the ConsultantTag to update in case it exists.
   */
  where: Prisma.ConsultantTagWhereUniqueInput
  /**
   * In case the ConsultantTag found by the `where` argument doesn't exist, create a new ConsultantTag with this data.
   */
  create: Prisma.XOR<Prisma.ConsultantTagCreateInput, Prisma.ConsultantTagUncheckedCreateInput>
  /**
   * In case the ConsultantTag was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ConsultantTagUpdateInput, Prisma.ConsultantTagUncheckedUpdateInput>
}

/**
 * ConsultantTag delete
 */
export type ConsultantTagDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConsultantTag
   */
  select?: Prisma.ConsultantTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConsultantTag
   */
  omit?: Prisma.ConsultantTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsultantTagInclude<ExtArgs> | null
  /**
   * Filter which ConsultantTag to delete.
   */
  where: Prisma.ConsultantTagWhereUniqueInput
}

/**
 * ConsultantTag deleteMany
 */
export type ConsultantTagDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ConsultantTags to delete
   */
  where?: Prisma.ConsultantTagWhereInput
  /**
   * Limit how many ConsultantTags to delete.
   */
  limit?: number
}

/**
 * ConsultantTag.users
 */
export type ConsultantTag$usersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
  orderBy?: Prisma.UserOrderByWithRelationInput | Prisma.UserOrderByWithRelationInput[]
  cursor?: Prisma.UserWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserScalarFieldEnum | Prisma.UserScalarFieldEnum[]
}

/**
 * ConsultantTag without action
 */
export type ConsultantTagDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConsultantTag
   */
  select?: Prisma.ConsultantTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ConsultantTag
   */
  omit?: Prisma.ConsultantTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsultantTagInclude<ExtArgs> | null
}
