
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserSlots` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserSlots
 * 
 */
export type UserSlotsModel = runtime.Types.Result.DefaultSelection<Prisma.$UserSlotsPayload>

export type AggregateUserSlots = {
  _count: UserSlotsCountAggregateOutputType | null
  _avg: UserSlotsAvgAggregateOutputType | null
  _sum: UserSlotsSumAggregateOutputType | null
  _min: UserSlotsMinAggregateOutputType | null
  _max: UserSlotsMaxAggregateOutputType | null
}

export type UserSlotsAvgAggregateOutputType = {
  dayOfWeek: number | null
}

export type UserSlotsSumAggregateOutputType = {
  dayOfWeek: number | null
}

export type UserSlotsMinAggregateOutputType = {
  id: string | null
  userId: string | null
  clientId: string | null
  dayOfWeek: number | null
  startTime: Date | null
  endTime: Date | null
}

export type UserSlotsMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  clientId: string | null
  dayOfWeek: number | null
  startTime: Date | null
  endTime: Date | null
}

export type UserSlotsCountAggregateOutputType = {
  id: number
  userId: number
  clientId: number
  dayOfWeek: number
  startTime: number
  endTime: number
  _all: number
}


export type UserSlotsAvgAggregateInputType = {
  dayOfWeek?: true
}

export type UserSlotsSumAggregateInputType = {
  dayOfWeek?: true
}

export type UserSlotsMinAggregateInputType = {
  id?: true
  userId?: true
  clientId?: true
  dayOfWeek?: true
  startTime?: true
  endTime?: true
}

export type UserSlotsMaxAggregateInputType = {
  id?: true
  userId?: true
  clientId?: true
  dayOfWeek?: true
  startTime?: true
  endTime?: true
}

export type UserSlotsCountAggregateInputType = {
  id?: true
  userId?: true
  clientId?: true
  dayOfWeek?: true
  startTime?: true
  endTime?: true
  _all?: true
}

export type UserSlotsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserSlots to aggregate.
   */
  where?: Prisma.UserSlotsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserSlots to fetch.
   */
  orderBy?: Prisma.UserSlotsOrderByWithRelationInput | Prisma.UserSlotsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserSlotsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserSlots
  **/
  _count?: true | UserSlotsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserSlotsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserSlotsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserSlotsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserSlotsMaxAggregateInputType
}

export type GetUserSlotsAggregateType<T extends UserSlotsAggregateArgs> = {
      [P in keyof T & keyof AggregateUserSlots]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserSlots[P]>
    : Prisma.GetScalarType<T[P], AggregateUserSlots[P]>
}




export type UserSlotsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserSlotsWhereInput
  orderBy?: Prisma.UserSlotsOrderByWithAggregationInput | Prisma.UserSlotsOrderByWithAggregationInput[]
  by: Prisma.UserSlotsScalarFieldEnum[] | Prisma.UserSlotsScalarFieldEnum
  having?: Prisma.UserSlotsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserSlotsCountAggregateInputType | true
  _avg?: UserSlotsAvgAggregateInputType
  _sum?: UserSlotsSumAggregateInputType
  _min?: UserSlotsMinAggregateInputType
  _max?: UserSlotsMaxAggregateInputType
}

export type UserSlotsGroupByOutputType = {
  id: string
  userId: string
  clientId: string | null
  dayOfWeek: number
  startTime: Date
  endTime: Date
  _count: UserSlotsCountAggregateOutputType | null
  _avg: UserSlotsAvgAggregateOutputType | null
  _sum: UserSlotsSumAggregateOutputType | null
  _min: UserSlotsMinAggregateOutputType | null
  _max: UserSlotsMaxAggregateOutputType | null
}

export type GetUserSlotsGroupByPayload<T extends UserSlotsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserSlotsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserSlotsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserSlotsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserSlotsGroupByOutputType[P]>
      }
    >
  >



export type UserSlotsWhereInput = {
  AND?: Prisma.UserSlotsWhereInput | Prisma.UserSlotsWhereInput[]
  OR?: Prisma.UserSlotsWhereInput[]
  NOT?: Prisma.UserSlotsWhereInput | Prisma.UserSlotsWhereInput[]
  id?: Prisma.StringFilter<"UserSlots"> | string
  userId?: Prisma.StringFilter<"UserSlots"> | string
  clientId?: Prisma.StringNullableFilter<"UserSlots"> | string | null
  dayOfWeek?: Prisma.IntFilter<"UserSlots"> | number
  startTime?: Prisma.DateTimeFilter<"UserSlots"> | Date | string
  endTime?: Prisma.DateTimeFilter<"UserSlots"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  client?: Prisma.XOR<Prisma.ClientNullableScalarRelationFilter, Prisma.ClientWhereInput> | null
}

export type UserSlotsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  clientId?: Prisma.SortOrderInput | Prisma.SortOrder
  dayOfWeek?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  client?: Prisma.ClientOrderByWithRelationInput
}

export type UserSlotsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.UserSlotsWhereInput | Prisma.UserSlotsWhereInput[]
  OR?: Prisma.UserSlotsWhereInput[]
  NOT?: Prisma.UserSlotsWhereInput | Prisma.UserSlotsWhereInput[]
  userId?: Prisma.StringFilter<"UserSlots"> | string
  clientId?: Prisma.StringNullableFilter<"UserSlots"> | string | null
  dayOfWeek?: Prisma.IntFilter<"UserSlots"> | number
  startTime?: Prisma.DateTimeFilter<"UserSlots"> | Date | string
  endTime?: Prisma.DateTimeFilter<"UserSlots"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  client?: Prisma.XOR<Prisma.ClientNullableScalarRelationFilter, Prisma.ClientWhereInput> | null
}, "id">

export type UserSlotsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  clientId?: Prisma.SortOrderInput | Prisma.SortOrder
  dayOfWeek?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  _count?: Prisma.UserSlotsCountOrderByAggregateInput
  _avg?: Prisma.UserSlotsAvgOrderByAggregateInput
  _max?: Prisma.UserSlotsMaxOrderByAggregateInput
  _min?: Prisma.UserSlotsMinOrderByAggregateInput
  _sum?: Prisma.UserSlotsSumOrderByAggregateInput
}

export type UserSlotsScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserSlotsScalarWhereWithAggregatesInput | Prisma.UserSlotsScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserSlotsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserSlotsScalarWhereWithAggregatesInput | Prisma.UserSlotsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"UserSlots"> | string
  userId?: Prisma.StringWithAggregatesFilter<"UserSlots"> | string
  clientId?: Prisma.StringNullableWithAggregatesFilter<"UserSlots"> | string | null
  dayOfWeek?: Prisma.IntWithAggregatesFilter<"UserSlots"> | number
  startTime?: Prisma.DateTimeWithAggregatesFilter<"UserSlots"> | Date | string
  endTime?: Prisma.DateTimeWithAggregatesFilter<"UserSlots"> | Date | string
}

export type UserSlotsCreateInput = {
  id?: string
  dayOfWeek: number
  startTime: Date | string
  endTime: Date | string
  user: Prisma.UserCreateNestedOneWithoutSlotsInput
  client?: Prisma.ClientCreateNestedOneWithoutSlotsInput
}

export type UserSlotsUncheckedCreateInput = {
  id?: string
  userId: string
  clientId?: string | null
  dayOfWeek: number
  startTime: Date | string
  endTime: Date | string
}

export type UserSlotsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayOfWeek?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSlotsNestedInput
  client?: Prisma.ClientUpdateOneWithoutSlotsNestedInput
}

export type UserSlotsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dayOfWeek?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserSlotsCreateManyInput = {
  id?: string
  userId: string
  clientId?: string | null
  dayOfWeek: number
  startTime: Date | string
  endTime: Date | string
}

export type UserSlotsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayOfWeek?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserSlotsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dayOfWeek?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserSlotsListRelationFilter = {
  every?: Prisma.UserSlotsWhereInput
  some?: Prisma.UserSlotsWhereInput
  none?: Prisma.UserSlotsWhereInput
}

export type UserSlotsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserSlotsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  dayOfWeek?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
}

export type UserSlotsAvgOrderByAggregateInput = {
  dayOfWeek?: Prisma.SortOrder
}

export type UserSlotsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  dayOfWeek?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
}

export type UserSlotsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  dayOfWeek?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
}

export type UserSlotsSumOrderByAggregateInput = {
  dayOfWeek?: Prisma.SortOrder
}

export type UserSlotsCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserSlotsCreateWithoutUserInput, Prisma.UserSlotsUncheckedCreateWithoutUserInput> | Prisma.UserSlotsCreateWithoutUserInput[] | Prisma.UserSlotsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserSlotsCreateOrConnectWithoutUserInput | Prisma.UserSlotsCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserSlotsCreateManyUserInputEnvelope
  connect?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
}

export type UserSlotsUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserSlotsCreateWithoutUserInput, Prisma.UserSlotsUncheckedCreateWithoutUserInput> | Prisma.UserSlotsCreateWithoutUserInput[] | Prisma.UserSlotsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserSlotsCreateOrConnectWithoutUserInput | Prisma.UserSlotsCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserSlotsCreateManyUserInputEnvelope
  connect?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
}

export type UserSlotsUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserSlotsCreateWithoutUserInput, Prisma.UserSlotsUncheckedCreateWithoutUserInput> | Prisma.UserSlotsCreateWithoutUserInput[] | Prisma.UserSlotsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserSlotsCreateOrConnectWithoutUserInput | Prisma.UserSlotsCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserSlotsUpsertWithWhereUniqueWithoutUserInput | Prisma.UserSlotsUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserSlotsCreateManyUserInputEnvelope
  set?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
  disconnect?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
  delete?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
  connect?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
  update?: Prisma.UserSlotsUpdateWithWhereUniqueWithoutUserInput | Prisma.UserSlotsUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserSlotsUpdateManyWithWhereWithoutUserInput | Prisma.UserSlotsUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserSlotsScalarWhereInput | Prisma.UserSlotsScalarWhereInput[]
}

export type UserSlotsUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserSlotsCreateWithoutUserInput, Prisma.UserSlotsUncheckedCreateWithoutUserInput> | Prisma.UserSlotsCreateWithoutUserInput[] | Prisma.UserSlotsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserSlotsCreateOrConnectWithoutUserInput | Prisma.UserSlotsCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserSlotsUpsertWithWhereUniqueWithoutUserInput | Prisma.UserSlotsUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserSlotsCreateManyUserInputEnvelope
  set?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
  disconnect?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
  delete?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
  connect?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
  update?: Prisma.UserSlotsUpdateWithWhereUniqueWithoutUserInput | Prisma.UserSlotsUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserSlotsUpdateManyWithWhereWithoutUserInput | Prisma.UserSlotsUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserSlotsScalarWhereInput | Prisma.UserSlotsScalarWhereInput[]
}

export type UserSlotsCreateNestedManyWithoutClientInput = {
  create?: Prisma.XOR<Prisma.UserSlotsCreateWithoutClientInput, Prisma.UserSlotsUncheckedCreateWithoutClientInput> | Prisma.UserSlotsCreateWithoutClientInput[] | Prisma.UserSlotsUncheckedCreateWithoutClientInput[]
  connectOrCreate?: Prisma.UserSlotsCreateOrConnectWithoutClientInput | Prisma.UserSlotsCreateOrConnectWithoutClientInput[]
  createMany?: Prisma.UserSlotsCreateManyClientInputEnvelope
  connect?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
}

export type UserSlotsUncheckedCreateNestedManyWithoutClientInput = {
  create?: Prisma.XOR<Prisma.UserSlotsCreateWithoutClientInput, Prisma.UserSlotsUncheckedCreateWithoutClientInput> | Prisma.UserSlotsCreateWithoutClientInput[] | Prisma.UserSlotsUncheckedCreateWithoutClientInput[]
  connectOrCreate?: Prisma.UserSlotsCreateOrConnectWithoutClientInput | Prisma.UserSlotsCreateOrConnectWithoutClientInput[]
  createMany?: Prisma.UserSlotsCreateManyClientInputEnvelope
  connect?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
}

export type UserSlotsUpdateManyWithoutClientNestedInput = {
  create?: Prisma.XOR<Prisma.UserSlotsCreateWithoutClientInput, Prisma.UserSlotsUncheckedCreateWithoutClientInput> | Prisma.UserSlotsCreateWithoutClientInput[] | Prisma.UserSlotsUncheckedCreateWithoutClientInput[]
  connectOrCreate?: Prisma.UserSlotsCreateOrConnectWithoutClientInput | Prisma.UserSlotsCreateOrConnectWithoutClientInput[]
  upsert?: Prisma.UserSlotsUpsertWithWhereUniqueWithoutClientInput | Prisma.UserSlotsUpsertWithWhereUniqueWithoutClientInput[]
  createMany?: Prisma.UserSlotsCreateManyClientInputEnvelope
  set?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
  disconnect?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
  delete?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
  connect?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
  update?: Prisma.UserSlotsUpdateWithWhereUniqueWithoutClientInput | Prisma.UserSlotsUpdateWithWhereUniqueWithoutClientInput[]
  updateMany?: Prisma.UserSlotsUpdateManyWithWhereWithoutClientInput | Prisma.UserSlotsUpdateManyWithWhereWithoutClientInput[]
  deleteMany?: Prisma.UserSlotsScalarWhereInput | Prisma.UserSlotsScalarWhereInput[]
}

export type UserSlotsUncheckedUpdateManyWithoutClientNestedInput = {
  create?: Prisma.XOR<Prisma.UserSlotsCreateWithoutClientInput, Prisma.UserSlotsUncheckedCreateWithoutClientInput> | Prisma.UserSlotsCreateWithoutClientInput[] | Prisma.UserSlotsUncheckedCreateWithoutClientInput[]
  connectOrCreate?: Prisma.UserSlotsCreateOrConnectWithoutClientInput | Prisma.UserSlotsCreateOrConnectWithoutClientInput[]
  upsert?: Prisma.UserSlotsUpsertWithWhereUniqueWithoutClientInput | Prisma.UserSlotsUpsertWithWhereUniqueWithoutClientInput[]
  createMany?: Prisma.UserSlotsCreateManyClientInputEnvelope
  set?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
  disconnect?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
  delete?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
  connect?: Prisma.UserSlotsWhereUniqueInput | Prisma.UserSlotsWhereUniqueInput[]
  update?: Prisma.UserSlotsUpdateWithWhereUniqueWithoutClientInput | Prisma.UserSlotsUpdateWithWhereUniqueWithoutClientInput[]
  updateMany?: Prisma.UserSlotsUpdateManyWithWhereWithoutClientInput | Prisma.UserSlotsUpdateManyWithWhereWithoutClientInput[]
  deleteMany?: Prisma.UserSlotsScalarWhereInput | Prisma.UserSlotsScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type UserSlotsCreateWithoutUserInput = {
  id?: string
  dayOfWeek: number
  startTime: Date | string
  endTime: Date | string
  client?: Prisma.ClientCreateNestedOneWithoutSlotsInput
}

export type UserSlotsUncheckedCreateWithoutUserInput = {
  id?: string
  clientId?: string | null
  dayOfWeek: number
  startTime: Date | string
  endTime: Date | string
}

export type UserSlotsCreateOrConnectWithoutUserInput = {
  where: Prisma.UserSlotsWhereUniqueInput
  create: Prisma.XOR<Prisma.UserSlotsCreateWithoutUserInput, Prisma.UserSlotsUncheckedCreateWithoutUserInput>
}

export type UserSlotsCreateManyUserInputEnvelope = {
  data: Prisma.UserSlotsCreateManyUserInput | Prisma.UserSlotsCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserSlotsUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserSlotsWhereUniqueInput
  update: Prisma.XOR<Prisma.UserSlotsUpdateWithoutUserInput, Prisma.UserSlotsUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserSlotsCreateWithoutUserInput, Prisma.UserSlotsUncheckedCreateWithoutUserInput>
}

export type UserSlotsUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserSlotsWhereUniqueInput
  data: Prisma.XOR<Prisma.UserSlotsUpdateWithoutUserInput, Prisma.UserSlotsUncheckedUpdateWithoutUserInput>
}

export type UserSlotsUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserSlotsScalarWhereInput
  data: Prisma.XOR<Prisma.UserSlotsUpdateManyMutationInput, Prisma.UserSlotsUncheckedUpdateManyWithoutUserInput>
}

export type UserSlotsScalarWhereInput = {
  AND?: Prisma.UserSlotsScalarWhereInput | Prisma.UserSlotsScalarWhereInput[]
  OR?: Prisma.UserSlotsScalarWhereInput[]
  NOT?: Prisma.UserSlotsScalarWhereInput | Prisma.UserSlotsScalarWhereInput[]
  id?: Prisma.StringFilter<"UserSlots"> | string
  userId?: Prisma.StringFilter<"UserSlots"> | string
  clientId?: Prisma.StringNullableFilter<"UserSlots"> | string | null
  dayOfWeek?: Prisma.IntFilter<"UserSlots"> | number
  startTime?: Prisma.DateTimeFilter<"UserSlots"> | Date | string
  endTime?: Prisma.DateTimeFilter<"UserSlots"> | Date | string
}

export type UserSlotsCreateWithoutClientInput = {
  id?: string
  dayOfWeek: number
  startTime: Date | string
  endTime: Date | string
  user: Prisma.UserCreateNestedOneWithoutSlotsInput
}

export type UserSlotsUncheckedCreateWithoutClientInput = {
  id?: string
  userId: string
  dayOfWeek: number
  startTime: Date | string
  endTime: Date | string
}

export type UserSlotsCreateOrConnectWithoutClientInput = {
  where: Prisma.UserSlotsWhereUniqueInput
  create: Prisma.XOR<Prisma.UserSlotsCreateWithoutClientInput, Prisma.UserSlotsUncheckedCreateWithoutClientInput>
}

export type UserSlotsCreateManyClientInputEnvelope = {
  data: Prisma.UserSlotsCreateManyClientInput | Prisma.UserSlotsCreateManyClientInput[]
  skipDuplicates?: boolean
}

export type UserSlotsUpsertWithWhereUniqueWithoutClientInput = {
  where: Prisma.UserSlotsWhereUniqueInput
  update: Prisma.XOR<Prisma.UserSlotsUpdateWithoutClientInput, Prisma.UserSlotsUncheckedUpdateWithoutClientInput>
  create: Prisma.XOR<Prisma.UserSlotsCreateWithoutClientInput, Prisma.UserSlotsUncheckedCreateWithoutClientInput>
}

export type UserSlotsUpdateWithWhereUniqueWithoutClientInput = {
  where: Prisma.UserSlotsWhereUniqueInput
  data: Prisma.XOR<Prisma.UserSlotsUpdateWithoutClientInput, Prisma.UserSlotsUncheckedUpdateWithoutClientInput>
}

export type UserSlotsUpdateManyWithWhereWithoutClientInput = {
  where: Prisma.UserSlotsScalarWhereInput
  data: Prisma.XOR<Prisma.UserSlotsUpdateManyMutationInput, Prisma.UserSlotsUncheckedUpdateManyWithoutClientInput>
}

export type UserSlotsCreateManyUserInput = {
  id?: string
  clientId?: string | null
  dayOfWeek: number
  startTime: Date | string
  endTime: Date | string
}

export type UserSlotsUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayOfWeek?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  client?: Prisma.ClientUpdateOneWithoutSlotsNestedInput
}

export type UserSlotsUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dayOfWeek?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserSlotsUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  dayOfWeek?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserSlotsCreateManyClientInput = {
  id?: string
  userId: string
  dayOfWeek: number
  startTime: Date | string
  endTime: Date | string
}

export type UserSlotsUpdateWithoutClientInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  dayOfWeek?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSlotsNestedInput
}

export type UserSlotsUncheckedUpdateWithoutClientInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  dayOfWeek?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserSlotsUncheckedUpdateManyWithoutClientInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  dayOfWeek?: Prisma.IntFieldUpdateOperationsInput | number
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UserSlotsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  clientId?: boolean
  dayOfWeek?: boolean
  startTime?: boolean
  endTime?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  client?: boolean | Prisma.UserSlots$clientArgs<ExtArgs>
}, ExtArgs["result"]["userSlots"]>

export type UserSlotsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  clientId?: boolean
  dayOfWeek?: boolean
  startTime?: boolean
  endTime?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  client?: boolean | Prisma.UserSlots$clientArgs<ExtArgs>
}, ExtArgs["result"]["userSlots"]>

export type UserSlotsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  clientId?: boolean
  dayOfWeek?: boolean
  startTime?: boolean
  endTime?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  client?: boolean | Prisma.UserSlots$clientArgs<ExtArgs>
}, ExtArgs["result"]["userSlots"]>

export type UserSlotsSelectScalar = {
  id?: boolean
  userId?: boolean
  clientId?: boolean
  dayOfWeek?: boolean
  startTime?: boolean
  endTime?: boolean
}

export type UserSlotsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "clientId" | "dayOfWeek" | "startTime" | "endTime", ExtArgs["result"]["userSlots"]>
export type UserSlotsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  client?: boolean | Prisma.UserSlots$clientArgs<ExtArgs>
}
export type UserSlotsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  client?: boolean | Prisma.UserSlots$clientArgs<ExtArgs>
}
export type UserSlotsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  client?: boolean | Prisma.UserSlots$clientArgs<ExtArgs>
}

export type $UserSlotsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserSlots"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    client: Prisma.$ClientPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    clientId: string | null
    dayOfWeek: number
    startTime: Date
    endTime: Date
  }, ExtArgs["result"]["userSlots"]>
  composites: {}
}

export type UserSlotsGetPayload<S extends boolean | null | undefined | UserSlotsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserSlotsPayload, S>

export type UserSlotsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserSlotsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserSlotsCountAggregateInputType | true
  }

export interface UserSlotsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserSlots'], meta: { name: 'UserSlots' } }
  /**
   * Find zero or one UserSlots that matches the filter.
   * @param {UserSlotsFindUniqueArgs} args - Arguments to find a UserSlots
   * @example
   * // Get one UserSlots
   * const userSlots = await prisma.userSlots.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserSlotsFindUniqueArgs>(args: Prisma.SelectSubset<T, UserSlotsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserSlotsClient<runtime.Types.Result.GetResult<Prisma.$UserSlotsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserSlots that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserSlotsFindUniqueOrThrowArgs} args - Arguments to find a UserSlots
   * @example
   * // Get one UserSlots
   * const userSlots = await prisma.userSlots.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserSlotsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserSlotsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserSlotsClient<runtime.Types.Result.GetResult<Prisma.$UserSlotsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserSlots that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserSlotsFindFirstArgs} args - Arguments to find a UserSlots
   * @example
   * // Get one UserSlots
   * const userSlots = await prisma.userSlots.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserSlotsFindFirstArgs>(args?: Prisma.SelectSubset<T, UserSlotsFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserSlotsClient<runtime.Types.Result.GetResult<Prisma.$UserSlotsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserSlots that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserSlotsFindFirstOrThrowArgs} args - Arguments to find a UserSlots
   * @example
   * // Get one UserSlots
   * const userSlots = await prisma.userSlots.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserSlotsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserSlotsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserSlotsClient<runtime.Types.Result.GetResult<Prisma.$UserSlotsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserSlots that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserSlotsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserSlots
   * const userSlots = await prisma.userSlots.findMany()
   * 
   * // Get first 10 UserSlots
   * const userSlots = await prisma.userSlots.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const userSlotsWithIdOnly = await prisma.userSlots.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends UserSlotsFindManyArgs>(args?: Prisma.SelectSubset<T, UserSlotsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserSlotsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserSlots.
   * @param {UserSlotsCreateArgs} args - Arguments to create a UserSlots.
   * @example
   * // Create one UserSlots
   * const UserSlots = await prisma.userSlots.create({
   *   data: {
   *     // ... data to create a UserSlots
   *   }
   * })
   * 
   */
  create<T extends UserSlotsCreateArgs>(args: Prisma.SelectSubset<T, UserSlotsCreateArgs<ExtArgs>>): Prisma.Prisma__UserSlotsClient<runtime.Types.Result.GetResult<Prisma.$UserSlotsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserSlots.
   * @param {UserSlotsCreateManyArgs} args - Arguments to create many UserSlots.
   * @example
   * // Create many UserSlots
   * const userSlots = await prisma.userSlots.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserSlotsCreateManyArgs>(args?: Prisma.SelectSubset<T, UserSlotsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserSlots and returns the data saved in the database.
   * @param {UserSlotsCreateManyAndReturnArgs} args - Arguments to create many UserSlots.
   * @example
   * // Create many UserSlots
   * const userSlots = await prisma.userSlots.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserSlots and only return the `id`
   * const userSlotsWithIdOnly = await prisma.userSlots.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserSlotsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserSlotsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserSlotsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserSlots.
   * @param {UserSlotsDeleteArgs} args - Arguments to delete one UserSlots.
   * @example
   * // Delete one UserSlots
   * const UserSlots = await prisma.userSlots.delete({
   *   where: {
   *     // ... filter to delete one UserSlots
   *   }
   * })
   * 
   */
  delete<T extends UserSlotsDeleteArgs>(args: Prisma.SelectSubset<T, UserSlotsDeleteArgs<ExtArgs>>): Prisma.Prisma__UserSlotsClient<runtime.Types.Result.GetResult<Prisma.$UserSlotsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserSlots.
   * @param {UserSlotsUpdateArgs} args - Arguments to update one UserSlots.
   * @example
   * // Update one UserSlots
   * const userSlots = await prisma.userSlots.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserSlotsUpdateArgs>(args: Prisma.SelectSubset<T, UserSlotsUpdateArgs<ExtArgs>>): Prisma.Prisma__UserSlotsClient<runtime.Types.Result.GetResult<Prisma.$UserSlotsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserSlots.
   * @param {UserSlotsDeleteManyArgs} args - Arguments to filter UserSlots to delete.
   * @example
   * // Delete a few UserSlots
   * const { count } = await prisma.userSlots.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserSlotsDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserSlotsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserSlots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserSlotsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserSlots
   * const userSlots = await prisma.userSlots.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserSlotsUpdateManyArgs>(args: Prisma.SelectSubset<T, UserSlotsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserSlots and returns the data updated in the database.
   * @param {UserSlotsUpdateManyAndReturnArgs} args - Arguments to update many UserSlots.
   * @example
   * // Update many UserSlots
   * const userSlots = await prisma.userSlots.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserSlots and only return the `id`
   * const userSlotsWithIdOnly = await prisma.userSlots.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserSlotsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserSlotsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserSlotsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserSlots.
   * @param {UserSlotsUpsertArgs} args - Arguments to update or create a UserSlots.
   * @example
   * // Update or create a UserSlots
   * const userSlots = await prisma.userSlots.upsert({
   *   create: {
   *     // ... data to create a UserSlots
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserSlots we want to update
   *   }
   * })
   */
  upsert<T extends UserSlotsUpsertArgs>(args: Prisma.SelectSubset<T, UserSlotsUpsertArgs<ExtArgs>>): Prisma.Prisma__UserSlotsClient<runtime.Types.Result.GetResult<Prisma.$UserSlotsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserSlots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserSlotsCountArgs} args - Arguments to filter UserSlots to count.
   * @example
   * // Count the number of UserSlots
   * const count = await prisma.userSlots.count({
   *   where: {
   *     // ... the filter for the UserSlots we want to count
   *   }
   * })
  **/
  count<T extends UserSlotsCountArgs>(
    args?: Prisma.Subset<T, UserSlotsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserSlotsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserSlots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserSlotsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserSlotsAggregateArgs>(args: Prisma.Subset<T, UserSlotsAggregateArgs>): Prisma.PrismaPromise<GetUserSlotsAggregateType<T>>

  /**
   * Group by UserSlots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserSlotsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserSlotsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserSlotsGroupByArgs['orderBy'] }
      : { orderBy?: UserSlotsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserSlotsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserSlotsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserSlots model
 */
readonly fields: UserSlotsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserSlots.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserSlotsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  client<T extends Prisma.UserSlots$clientArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserSlots$clientArgs<ExtArgs>>): Prisma.Prisma__ClientClient<runtime.Types.Result.GetResult<Prisma.$ClientPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserSlots model
 */
export interface UserSlotsFieldRefs {
  readonly id: Prisma.FieldRef<"UserSlots", 'String'>
  readonly userId: Prisma.FieldRef<"UserSlots", 'String'>
  readonly clientId: Prisma.FieldRef<"UserSlots", 'String'>
  readonly dayOfWeek: Prisma.FieldRef<"UserSlots", 'Int'>
  readonly startTime: Prisma.FieldRef<"UserSlots", 'DateTime'>
  readonly endTime: Prisma.FieldRef<"UserSlots", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserSlots findUnique
 */
export type UserSlotsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserSlots
   */
  select?: Prisma.UserSlotsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSlots
   */
  omit?: Prisma.UserSlotsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSlotsInclude<ExtArgs> | null
  /**
   * Filter, which UserSlots to fetch.
   */
  where: Prisma.UserSlotsWhereUniqueInput
}

/**
 * UserSlots findUniqueOrThrow
 */
export type UserSlotsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserSlots
   */
  select?: Prisma.UserSlotsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSlots
   */
  omit?: Prisma.UserSlotsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSlotsInclude<ExtArgs> | null
  /**
   * Filter, which UserSlots to fetch.
   */
  where: Prisma.UserSlotsWhereUniqueInput
}

/**
 * UserSlots findFirst
 */
export type UserSlotsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserSlots
   */
  select?: Prisma.UserSlotsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSlots
   */
  omit?: Prisma.UserSlotsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSlotsInclude<ExtArgs> | null
  /**
   * Filter, which UserSlots to fetch.
   */
  where?: Prisma.UserSlotsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserSlots to fetch.
   */
  orderBy?: Prisma.UserSlotsOrderByWithRelationInput | Prisma.UserSlotsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserSlots.
   */
  cursor?: Prisma.UserSlotsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserSlots.
   */
  distinct?: Prisma.UserSlotsScalarFieldEnum | Prisma.UserSlotsScalarFieldEnum[]
}

/**
 * UserSlots findFirstOrThrow
 */
export type UserSlotsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserSlots
   */
  select?: Prisma.UserSlotsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSlots
   */
  omit?: Prisma.UserSlotsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSlotsInclude<ExtArgs> | null
  /**
   * Filter, which UserSlots to fetch.
   */
  where?: Prisma.UserSlotsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserSlots to fetch.
   */
  orderBy?: Prisma.UserSlotsOrderByWithRelationInput | Prisma.UserSlotsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserSlots.
   */
  cursor?: Prisma.UserSlotsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserSlots.
   */
  distinct?: Prisma.UserSlotsScalarFieldEnum | Prisma.UserSlotsScalarFieldEnum[]
}

/**
 * UserSlots findMany
 */
export type UserSlotsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserSlots
   */
  select?: Prisma.UserSlotsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSlots
   */
  omit?: Prisma.UserSlotsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSlotsInclude<ExtArgs> | null
  /**
   * Filter, which UserSlots to fetch.
   */
  where?: Prisma.UserSlotsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserSlots to fetch.
   */
  orderBy?: Prisma.UserSlotsOrderByWithRelationInput | Prisma.UserSlotsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserSlots.
   */
  cursor?: Prisma.UserSlotsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserSlots.
   */
  distinct?: Prisma.UserSlotsScalarFieldEnum | Prisma.UserSlotsScalarFieldEnum[]
}

/**
 * UserSlots create
 */
export type UserSlotsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserSlots
   */
  select?: Prisma.UserSlotsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSlots
   */
  omit?: Prisma.UserSlotsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSlotsInclude<ExtArgs> | null
  /**
   * The data needed to create a UserSlots.
   */
  data: Prisma.XOR<Prisma.UserSlotsCreateInput, Prisma.UserSlotsUncheckedCreateInput>
}

/**
 * UserSlots createMany
 */
export type UserSlotsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserSlots.
   */
  data: Prisma.UserSlotsCreateManyInput | Prisma.UserSlotsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserSlots createManyAndReturn
 */
export type UserSlotsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserSlots
   */
  select?: Prisma.UserSlotsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserSlots
   */
  omit?: Prisma.UserSlotsOmit<ExtArgs> | null
  /**
   * The data used to create many UserSlots.
   */
  data: Prisma.UserSlotsCreateManyInput | Prisma.UserSlotsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSlotsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserSlots update
 */
export type UserSlotsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserSlots
   */
  select?: Prisma.UserSlotsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSlots
   */
  omit?: Prisma.UserSlotsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSlotsInclude<ExtArgs> | null
  /**
   * The data needed to update a UserSlots.
   */
  data: Prisma.XOR<Prisma.UserSlotsUpdateInput, Prisma.UserSlotsUncheckedUpdateInput>
  /**
   * Choose, which UserSlots to update.
   */
  where: Prisma.UserSlotsWhereUniqueInput
}

/**
 * UserSlots updateMany
 */
export type UserSlotsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserSlots.
   */
  data: Prisma.XOR<Prisma.UserSlotsUpdateManyMutationInput, Prisma.UserSlotsUncheckedUpdateManyInput>
  /**
   * Filter which UserSlots to update
   */
  where?: Prisma.UserSlotsWhereInput
  /**
   * Limit how many UserSlots to update.
   */
  limit?: number
}

/**
 * UserSlots updateManyAndReturn
 */
export type UserSlotsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserSlots
   */
  select?: Prisma.UserSlotsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserSlots
   */
  omit?: Prisma.UserSlotsOmit<ExtArgs> | null
  /**
   * The data used to update UserSlots.
   */
  data: Prisma.XOR<Prisma.UserSlotsUpdateManyMutationInput, Prisma.UserSlotsUncheckedUpdateManyInput>
  /**
   * Filter which UserSlots to update
   */
  where?: Prisma.UserSlotsWhereInput
  /**
   * Limit how many UserSlots to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSlotsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserSlots upsert
 */
export type UserSlotsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserSlots
   */
  select?: Prisma.UserSlotsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSlots
   */
  omit?: Prisma.UserSlotsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSlotsInclude<ExtArgs> | null
  /**
   * The filter to search for the UserSlots to update in case it exists.
   */
  where: Prisma.UserSlotsWhereUniqueInput
  /**
   * In case the UserSlots found by the `where` argument doesn't exist, create a new UserSlots with this data.
   */
  create: Prisma.XOR<Prisma.UserSlotsCreateInput, Prisma.UserSlotsUncheckedCreateInput>
  /**
   * In case the UserSlots was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserSlotsUpdateInput, Prisma.UserSlotsUncheckedUpdateInput>
}

/**
 * UserSlots delete
 */
export type UserSlotsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserSlots
   */
  select?: Prisma.UserSlotsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSlots
   */
  omit?: Prisma.UserSlotsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSlotsInclude<ExtArgs> | null
  /**
   * Filter which UserSlots to delete.
   */
  where: Prisma.UserSlotsWhereUniqueInput
}

/**
 * UserSlots deleteMany
 */
export type UserSlotsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserSlots to delete
   */
  where?: Prisma.UserSlotsWhereInput
  /**
   * Limit how many UserSlots to delete.
   */
  limit?: number
}

/**
 * UserSlots.client
 */
export type UserSlots$clientArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Client
   */
  select?: Prisma.ClientSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Client
   */
  omit?: Prisma.ClientOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientInclude<ExtArgs> | null
  where?: Prisma.ClientWhereInput
}

/**
 * UserSlots without action
 */
export type UserSlotsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserSlots
   */
  select?: Prisma.UserSlotsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserSlots
   */
  omit?: Prisma.UserSlotsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserSlotsInclude<ExtArgs> | null
}
